### ISSUE TITLE
Trigger flux from git's CI/CD

### ISSUE THREAD

**Issue by apryiomka** [fluxcd/flux#3129] opened 2020-06-10 21:21 UTC
**Describe the feature**
I would to expose flux not as a pull mechanism, but a push. We want to push the entire manifest to flux and let the flux determine the difference vs having flux to pull form git repo directly.

**What would the new user story look like?**
We have a more complex way of creating manifests that is not simple static repo. We do generate certain things on fly as part of a build, not as part of a commit. Also we do run a set of validations once the manifest is deployed. Currently we want instead of flux pulling from the repo, rather push to flux once the manifests are generated and let flux to install the resources, then run validation step to confirm the working state of the cluster.

That does't work very well with flux pulling strategy.

**Comment by chaliy** [comment] 2020-06-14 15:49
Just hit this topic while looks for a solution to provision K8s resources that could be integrated in CD pipelines like circleci or gitlab-ci. 

Our use case is quite similar. We have a few pre-steps in circleci pipeline, then we need to provision k8s resources, about 15 helm releases, and few dozens of plain yaml or kustomize yamls.

It seems that for us ideal would be to have a cli packed as binary in docker image that we could run in our pipeline. From functional point of view, it seems like a fluxcd without operator and git pull bits.

**Comment by allanitis** [comment] 2020-10-07 09:38
Same use case here. We want to deploy one pod per user. If the user requests a new pod, then we will commit a new manifest to git, and flux will deploy the new release. 

Currently, we tell the user to wait while we wait for flux to ping git and see the new commit, which then deploys the new manifest.  

A webhook from git into flux (ie. like most other ci/cd tools), would solve this.

**Comment by stefanprodan** [comment] 2020-10-07 09:52
This is supported in Flux v2 see the webhooks guide https://toolkit.fluxcd.io/guides/webhook-receivers/

**Comment by kingdonb** [comment] 2021-02-22 20:58
Flux's model of reproducibility depends on being able to say what it deploys on the cluster is what comes from a manifest, in a source (repo), without any kind of (possibly turing-complete) interloper that may fail at runtime for arbitrary reasons, including external service dependencies or otherwise "clever" logic-bomb surprises that should have failed in CI.

If your goal is to notify Flux that a new commit is ready, use webhooks. If your goal is for Flux to apply something other than what is in the repository, you'll need to make this a CI process and possibly tell Flux to read something from a different place.

This is how we are recommending to handle manifest generation (a.k.a. `.flux.yaml`) in Flux v2. With a CI process like GitHub Actions, it is really easy to make a CI task that commits back to the repository. You can put generated manifests in a separate branch or repo, or even put them into a separate folder in a new commit on the same branch.

With other CIs, sure, it can be a little more complicated to commit back to git. You may need to go through some security process to enable write access from CI to your repository; but for Flux's architecture it is necessary for the manifests to come directly from a trusted source in order for Flux's security and validation models to work. If you don't like the idea of a separate branch in your repo for robot commits with generated manifests, you can use a different abstraction in Flux v2 like the Bucket source if it is more to your taste. In fact you can add many sources in Flux v2, (which of course you could never do in Flux v1!)

But it is important for security and auditability reasons that Flux does not receive complex instructions through a webhook, and mostly does not modify yamls in-flight (with the single exception of `envsubst`, an exception that compromises little).

We hope you can upgrade to Flux v2 and that it meets all your use cases! Flux v1 is in maintenance mode and will not receive new features; Flux v2 is at feature parity since 0.8 and we are recommending all interested users to upgrade as early as possible. Closing, as this is not a Flux v1 maintenance issue at this point.

**Closed by kingdonb** 2021-02-22 20:58 UTC
Labels: enhancement, flux2
