### ISSUE TITLE
Build error `make test` fail on mac

### ISSUE THREAD

**Issue by jwausle** [fluxcd/flux#3288] opened 2020-09-11 18:51 UTC
**Describe the bug**

`make test` fail with multiple failors

**To Reproduce**

```
$ git checkout master
$ make all
$ make test
```

**Expected behavior**

> No failor

**What I see instead**

```
--- FAIL: Test_InitContainer (1.00s)
    repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone638628939 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
         fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
        fatal: Die Gegenseite hat unerwartet abgebrochen.

--- FAIL: Test_FilterLogic (5.61s)
    --- FAIL: Test_FilterLogic/include_specific_service (1.03s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone243257488 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

    --- FAIL: Test_FilterLogic/exclude_specific_service (0.90s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone236957369 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

    --- FAIL: Test_FilterLogic/update_specific_image (0.95s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone053361814 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

    --- FAIL: Test_FilterLogic/skipped_&_service_is_pending (0.91s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone715134007 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

    --- FAIL: Test_FilterLogic/all_overrides_spec (0.94s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone966305516 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

    --- FAIL: Test_FilterLogic/service_not_in_repo (0.87s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone080691781 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

--- FAIL: Test_Force_lockedWorkload (2.80s)
    --- FAIL: Test_Force_lockedWorkload/force_ignores_service_lock_(--workload_--update-image) (0.82s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone514706706 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

    --- FAIL: Test_Force_lockedWorkload/force_does_not_ignore_lock_if_updating_all_workloads_(--all_--update-image) (0.69s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone058670179 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

    --- FAIL: Test_Force_lockedWorkload/force_ignores_service_lock_(--workload_--update-all-images) (0.65s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone258837640 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

    --- FAIL: Test_Force_lockedWorkload/force_does_not_ignore_lock_if_updating_all_workloads_(--all_--update-all-images) (0.64s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone517280273 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

--- FAIL: Test_Force_filteredContainer (2.59s)
    --- FAIL: Test_Force_filteredContainer/force_ignores_container_tag_pattern_(--workload_--update-image) (0.61s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone697157326 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

    --- FAIL: Test_Force_filteredContainer/force_ignores_container_tag_pattern_(--all_--update-image) (0.64s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone314994383 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

    --- FAIL: Test_Force_filteredContainer/force_complies_with_semver_when_updating_all_images_(--workload_--update-all-image) (0.65s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone577828708 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

    --- FAIL: Test_Force_filteredContainer/force_complies_with_semver_when_updating_all_images_(--all_--update-all-image) (0.69s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone702652957 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

--- FAIL: Test_ImageStatus (1.43s)
    --- FAIL: Test_ImageStatus/image_not_found (0.71s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone346892746 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

    --- FAIL: Test_ImageStatus/image_up_to_date (0.71s)
        repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone664574331 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
             fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
            fatal: Die Gegenseite hat unerwartet abgebrochen.

--- FAIL: Test_UpdateMultidoc (0.71s)
    repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone231057792 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
         fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
        fatal: Die Gegenseite hat unerwartet abgebrochen.

--- FAIL: Test_UpdateList (0.71s)
    repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone300860009 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
         fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
        fatal: Die Gegenseite hat unerwartet abgebrochen.

--- FAIL: Test_UpdateContainers (0.72s)
    repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone427612678 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
         fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
        fatal: Die Gegenseite hat unerwartet abgebrochen.

--- FAIL: Test_BadRelease (0.70s)
    repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone534016103 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
         fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
        fatal: Die Gegenseite hat unerwartet abgebrochen.

FAIL
FAIL	github.com/fluxcd/flux/pkg/release	16.307s
ok  	github.com/fluxcd/flux/pkg/remote	0.020s
ok  	github.com/fluxcd/flux/pkg/remote/rpc	0.024s
ok  	github.com/fluxcd/flux/pkg/resource	0.017s
?   	github.com/fluxcd/flux/pkg/ssh	[no test files]
--- FAIL: TestSync (1.01s)
    repo.go:92: git fetch --tags /var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/flux-gitclone172680086 [refs/notes/fluxtest:refs/notes/fluxtest]: fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden., full output:
         fatal: Konnte Remote-Referenz refs/notes/fluxtest nicht finden.
        fatal: Die Gegenseite hat unerwartet abgebrochen.

FAIL
FAIL	github.com/fluxcd/flux/pkg/sync	1.056s
ok  	github.com/fluxcd/flux/pkg/update	0.022s
FAIL
make: *** [test] Error 1
```

**Why is that bad?**

I cannot create unit test for a PR for issue #2568. 

**Additional context**

- OS: mac
- Flux version: current master
- Go version: go1.15.1 darwin/amd64
- Go env:

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/winter/Library/Caches/go-build"
GOENV="/Users/winter/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/winter/golang/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/winter/golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/winter/Git/flux/flux/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/06/0flx_c9x3rq5_knx4kr_tpt00000gp/T/go-build105177245=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by kingdonb** [comment] 2021-02-19 18:09
It seems reasonable to expect that make test fails on a mac, you should run it in a container or native Linux environment.

I was able to reproduce the issue, (though I got a different set of failures on my machine) I understand your frustration. Since Flux runs on Linux containers it can't be a priority to provide test scaffolds that run natively on other operating environments.

I ran the tests on a Fedora workstation machine with lots of dev tools preinstalled and it went fine (all passed). I also ran the tests in a container thinking "hey this is going to be easy" and it went not as fine.

```
$ docker run -it -v `pwd`:/flux -w /flux/ golang:1.15.8-alpine3.13 sh
# ... inside the container
$ apk add make bash git curl gcc gnupg musl-dev docker
$ make test
```

... I got this far before giving up, once I got to a failure resulting in missing docker binary, I realized that some tests depend on having a running Docker daemon, which I was not prepared to orchestrate inside of a Docker container today.

The second best way to run your tests for Flux is to open a pull request against fluxcd/flux, and our CI will run them for you.

**Comment by kingdonb** [comment] 2021-02-19 18:10
I'm going to close this for now, but I am open to a PR that provides better facilities for Mac user to test their Flux prerelease builds locally if you have any ideas about how that can be done. Thanks for the report.

**Closed by kingdonb** 2021-02-19 18:10 UTC
Labels: blocked-needs-validation, bug
