### ISSUE TITLE
Image with zero created timestamp

### ISSUE THREAD

**Issue by slamdev** [fluxcd/flux#2929] opened 2020-03-22 22:52 UTC
**Describe the bug**

Flux fails to update a deployment with new image. Docker inspect shows valid **created** value: `"Created": "2020-03-22T22:35:12.928157704Z"`

Images that causes the problem are open for public access:
```sh
docker image inspect docker.io/slamdev/backend
docker image inspect docker.io/slamdev/frontend
```

**To Reproduce**

Flux is installed using this bash script: https://github.com/slamdev/multicluster-gitops/blob/master/hacks/install-flux.sh

Repo with all the configuration: https://github.com/slamdev/multicluster-gitops

Steps to reproduce the behaviour:

**Expected behavior**

Flux sync images created via `docker build`.

**Logs**

```
flux-7f557bf5d8-mgls6 flux ts=2020-03-22T22:40:26.501525942Z caller=images.go:106 component=sync-loop workload=dev:deployment/backend-app container=app repo=docker.io/slamdev/backend pattern=glob:* current=docker.io/slamdev/backend warning="image with zero created timestamp" current="docker.io/slamdev/backend (0001-01-01 00:00:00 +0000 UTC)" latest="docker.io/slamdev/backend:fd9085 (2020-03-22 22:34:51.819427717 +0000 UTC)" action="skip container"
flux-7f557bf5d8-mgls6 flux ts=2020-03-22T22:40:26.501872881Z caller=images.go:106 component=sync-loop workload=dev:deployment/frontend-app container=app repo=docker.io/slamdev/frontend pattern=glob:* current=docker.io/slamdev/frontend warning="image with zero created timestamp" current="docker.io/slamdev/frontend (0001-01-01 00:00:00 +0000 UTC)" latest="docker.io/slamdev/frontend:9f5d89 (2020-03-22 22:34:59.677510478 +0000 UTC)" action="skip container"
```

**Additional context**

- Flux version: 1.18.0
- Kubernetes version: v1.14.10-gke.24
- Git provider: github
- Container registry provider: dockerhub

**Comment by hiddeco** [comment] 2020-03-22 23:04
If the workload currently does not have a tag set, can you please add this to see if it resolves the issue? Flux will not automate resources that do not have a tag defined (and are thus running on `latest`) as it only operates on immutable tags.

**Comment by slamdev** [comment] 2020-03-23 15:32
@hiddeco thanks, that helped. my bad: didn't read the instruction properly. 

Can you convert this issue to an improvement, so flux gives a proper message when the tag is "latest" or (as I found out experimentally) when the specified tag is not exist in the registry at all.

**Comment by dmarkey** [comment] 2020-04-14 15:02
I have a similar issue.

1. I have a deployment that is tracking glob:foo-* that is on foo-123
2. foo-123 gets deleted on the image store. but the deployment is still running
3. Cluster gets rebooted(on a schedule) and is now ImagePullBackoff
4. foo-456 is built but flux refuses to roll out due to "image with zero created timestamp" even though the deployment is already broken.

I've been trying to establish why my image wouldnt have a timestamp but I can't figure out why.

Only way to remedy the above scenario is to override the image directly in the manifest.

**Comment by renanqts** [comment] 2020-04-21 14:53
Same issue here. I'm trying to find a way at least to monitor this issue without check logs.

**Comment by mzupan** [comment] 2020-04-23 17:57
So I ran into something sort of the same.

I had this

```
  values:
    image:
      repository: #####.dkr.ecr.us-east-1.amazonaws.com/worker
      tag: 10
```

As the current release running. I did a `sync` and pushed a new tag `11` out and was getting the timestamp issue

I just added quotes around the tag to force it as a string and then ran `sync` again. Then flux picked up and did the update from 10->11

**Comment by inful** [comment] 2020-05-12 13:08
> I have a similar issue.
> 
> 1. I have a deployment that is tracking glob:foo-* that is on foo-123
> 2. foo-123 gets deleted on the image store. but the deployment is still running
> 3. Cluster gets rebooted(on a schedule) and is now ImagePullBackoff
> 4. foo-456 is built but flux refuses to roll out due to "image with zero created timestamp" even though the deployment is already broken.
> 
> I've been trying to establish why my image wouldnt have a timestamp but I can't figure out why.
> 
> Only way to remedy the above scenario is to override the image directly in the manifest.

I can confirme the observed  behaviour running flux 1.19.0. I can see why you do not want to consider images with zero created timestamp for replacement of existing images - but replacing images without a timestamp with a "newer" timestamp (I guess these would be equivalent with removed or no-existing images) would to me be the expected behaviour.

**Comment by masterkain** [comment] 2021-02-08 13:49
no solutions to this yet?

**Comment by kingdonb** [comment] 2021-02-19 13:20
Is #3417 possibly a duplicate of this report?

**Comment by inful** [comment] 2021-02-19 13:52
I do not think so, as reproducible builds seems to actually has a timestamp. In the behaviour described by @dmarkey  the originally deployed image is non-existent.

**Comment by kingdonb** [comment] 2021-02-19 13:56
Ah, I thought it might be the same issue since the message is "Image with zero created timestamp" and in reproducible build the timestamp is fixed, to a value of zero seconds (01-Jan-1970 00:00 UTC eg. epoch time is a zero timestamp.)

#3417 may still be the same issue, since semver sort apparently fails there based on the zero timestamp (no technical reason why it should from what I can see), and that issue wasn't posted with complete record of all the flux daemon logs, we can't be sure it doesn't have that message too. (I'd be a bit surprised if we don't find the same fix solves both problems.)

**Comment by inful** [comment] 2021-02-19 14:08
> Ah, I thought it might be the same issue since the message is "Image with zero created timestamp" and in reproducible build the timestamp is fixed, to a value of zero seconds (01-Jan-1970 00:00 UTC eg. epoch time is a zero timestamp.)
> 
> #3417 may still be the same issue, since semver sort apparently fails there based on the zero timestamp (no technical reason why it should from what I can see), and that issue wasn't posted with complete record of all the flux daemon logs, we can't be sure it doesn't have that message too. (I'd be a bit surprised if we don't find the same fix solves both problems.)

You might very well be correct in that assumption :)

**Comment by kingdonb** [comment] 2021-07-31 17:00
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!

**Closed by kingdonb** 2021-07-31 17:00 UTC
Labels: blocked, bug
