### ISSUE TITLE
Malformed YAML configuration blocks automated updates (flux:1.22.2)

### ISSUE THREAD

**Issue by cmfcruz** [fluxcd/flux#3484] opened 2021-05-20 18:53 UTC
**Describe the bug**

A malformed YAML configuration blocks automated updates.

We have multiple deployments set to automated updates but these deployments did not update to the latest versions.  We have a separate cluster with an identical setup that had no problems updating to the latest image versions.  We found that the cluster that was having automated update issues had a malformed YAML configuration file for one of the deployments.

This can be unexpected for some cases and can be a huge blocker for those who heavily rely on automated deployments.

**To Reproduce**

Steps to reproduce the behaviour:

1. Follow the standard [flux installation instructions](https://fluxcd.io/docs/installation/) and configure to use a standard git repository with Kubernetes configurations.
2. Automate one or two deployments.
3. Modify one of the deployments that is not automated to make a malformed YAML file.  Adding multiple document starts at the beginning of the file should do:
```
---
---
apiVersion: apps/v1
kind: Deployment
```
4. Release a new image with a higher semver for one of the automated deployments.
5. The automated deployment would not update to the latest version until the malformed YAML file is fixed.

**Expected behavior**

Automated deployments other than those with malformed YAML configuration files should still upgrade to the latest versions.

**Logs**

This is the offending error we encountered that led us to finding this issue:
`[flux-67d4d969c4-ntblk] ts=2021-05-19T18:41:44.757772803Z caller=loop.go:152 component=sync-loop jobID=1f20568a-48a5-f059-9923-246928d43758 state=done success=false err="applying changes: updating resource mynamespace:deployment/myservice in kubernetes/mynamespace/myservice/deployment.yml: [31688] Failed to execute script kubeyaml\nTraceback (most recent call last):\n File \"kubeyaml.py\", line 311, in <module>\n File \"kubeyaml.py\", line 304, in main\n File \"kubeyaml.py\", line 77, in apply_to_yaml\n File \"site-packages/ruamel/yaml/main.py\", line 454, in dump_all\n File \"kubeyaml.py\", line 84, in update_image\n File \"kubeyaml.py\", line 156, in manifests\nTypeError: 'NoneType' object is not subscriptable"`

**Additional context**

- Flux version: `1.22.2`
- Kubernetes version: `1.18 running on AWS EKS`
- Git provider: `Github`
- Container registry provider: `Dockerhub`

**Comment by kingdonb** [comment] 2021-05-20 19:28
Thank you for the report.

The `kubeyaml.py` file is parsing your YAML and acts as part of the Image Update automation feature. Flux has generally included guidance that recommends you validate your YAML with `kubeval` in a PR check before it is merged to production.

I'm not sure the behavior of Flux when presented with invalid YAML is something that is strictly documented. In Flux v2, there is built-in validation (which is actually meant to prevent any part of the commit from being applied when some part is invalid.)

In Flux v2 it can be enabled or disabled. In Flux v1, it's not really a feature extant within the internals of Flux -- there is no validation. I'm not sure there is a straightforward fix for this, or that we would necessarily agree about how it ought to work.

**Comment by cmfcruz** [comment] 2021-05-20 20:43
Thanks for the info. I'll add `kubeval` as one of our checks.

Our issue in this case is that a malformed YAML file of a single deployment can prevent the automated updates of the rest of the deployments.  We were expecting that each deployment are treated separately when being updated by flux. Maybe it's worth considering to just warn the user of malformed YAML files instead of completely blocking the updates of working deployments?

We'll check out Flux v2.  Flux v1 was working so well for us we didn't realize v2 was already out. Thanks again!

**Comment by kingdonb** [comment] 2021-05-23 13:59
Flux v2 is being recommended for production use, although the image automation feature is still technically in alpha, we're not expecting major changes to the way that it works at this point. Everything else from the Flux v2 "GitOps Toolkit" APIs are at least in Beta, which means there is a commitment to providing smooth transition for any forward upgrades.

I'd like to know a bit more about your Flux v1 report though before closing it out!

Is this report describing a regression from a previous version, or was that a new implementation of Flux you're planning/executing?

If you were trying to install Flux v1 as a new user, I'd also like to know when and how you arrived at that idea without tripping over some Flux v2 deprecation warnings or if they were not convincing enough to get you to try the new version first. We've been trying our best to put up big ugly banners on all the Flux v1 documentation to discourage new users from starting there (though it is still supported, we do not recommend new users to start with Flux v1 anymore because of the progress in v2.)

**Comment by cmfcruz** [comment] 2021-05-25 09:22
We experienced the issue since `1.21.X` and upgraded to `1.22.2` thinking that it may have been fixed at that version.  I didn't notice if we were having the same issue with earlier versions (we've been using flux for 1 year now going through multiple minor versions). We haven't tried Flux v2 yet since we were unaware of it. Flux v1 is working fine for us except for the time we encountered the problem above.  We are still using `1.22.2` now and it's running without hitches after fixing the problematic YAML file.

I'll share more info about our setup. First, the flux daemons are installed using the generated file from `fluxctl install`. This configuration is applied directly into the cluster. Second, We have a flux daemon to manage each namespace installed by the same process.  These daemons share the same git SSH key and Dockerhub account. We are not using the Flux Helm operator.

By the way, `kubeval` is no use to block this situation since the multiple document starts (`---`) just registers as an empty document. Multiple document starts is also valid as an empty document when tested with `kubectl apply -f <filename>.yml --dry-run=server`.

**Comment by kingdonb** [comment] 2021-06-01 18:30
That's unfortunate, `kubeyaml` is one of the deepest darkest crusty bits of old legacy parts of Flux.

Even if you were not using image automation, I don't know if there's any way to extricate kubeyaml from Flux v1.

It would be good to implement error checking ahead of kubeyaml, since it's going to barf on empty documents, we should at least be able to check for empty documents and make sure the output error reflects that an empty document blocked some progress. This is really blocking all progress... that's bad, so if there is any alert which we can raise, it should be flagging.

Just curious if you have implemented monitoring to alert and notify you to a steady state when Flux is not syncing fully?

**Comment by kingdonb** [comment] 2021-06-03 12:04
There are three alerts suggested in https://docs.fluxcd.io/en/1.22.2/references/monitoring/ for tracking the correct operation of Flux v1. If none of them are firing and this failure condition is not reported by the monitoring strategy, then I would suggest we can update the docs to add an alert that will catch it.

Generally `kubeyaml` behavior cannot be solved, or changed, without too much risk that we will change some important behavior of Flux v1. If you have found a gap in the suggested monitoring config, that's something we can definitely address without risk that we are going to break anyone's cluster or change behavior on their next Flux upgrade.

I'd like to hear back whether this will help, or if you have implemented monitoring. If I can find an alert definition that we should add to Prometheus docs, then I will submit it as a PR to the docs and we can recommend adding it. If the existing suggested alerts already fire when this condition is reached, I'm not sure there is any additional resolution I can add safely.

**Comment by kingdonb** [comment] 2021-06-08 17:20
Thanks for reporting this. I'm going to close the issue as it has been responded.

If there is anything else we can do for you, it can be reopened, or you are welcome to open a new issue. Thanks for using Flux!

**Closed by kingdonb** 2021-06-08 17:20 UTC
Labels: bug
