### ISSUE TITLE
On manually deleting resource, flux does not resync due to existing helm release

### ISSUE THREAD

**Issue by ahmadiq** [fluxcd/flux#1295] opened 2018-08-17 20:36 UTC
Trying out a mock scenario where a resource might be inadvertently deleted manually. For this case I deleted the deployment manually, but the helm operator was unable to sync because of the pre-existing release.

```
 ts=2018-08-17T20:09:23.052909974Z caller=releasesync.go:314 component=releasesync info="Installing manually deleted Chart release operators-operators (namespace operators)"
ts=2018-08-17T20:09:23.053003329Z caller=release.go:154 component=release info="releaseName= operators-operators, action=CREATE, install options: {DryRun:false ReuseName:false}"
ts=2018-08-17T20:09:23.08776788Z caller=release.go:196 component=release error="Chart release failed: operators-operators: &amp;status.statusError{Code:2, Message:\"a release named operators-operators already exists.\\nRun: helm ls --all operators-operators; to check the status of the release\\nOr run: helm del --purge operators-operators; to delete it\", Details:[]*any.Any(nil)}"
ts=2018-08-17T20:09:23.087840761Z caller=chartsync.go:117 component=chartsync error="Failure to do manual release sync: syncing cluster after manual chart release changes: rpc error: code = Unknown desc = a release named operators-operators already exists.\nRun: helm ls --all operators-operators; to check the status of the release\nOr run: helm del --purge operators-operators; to delete it" 
```

**Comment by squaremo** [comment] 2018-09-27 16:18
Would #1344 have helped with this problem? It's included in helm-operator 0.2.1, so you could rerun your experiment with that to find out.

**Comment by captncraig** [comment] 2019-01-22 02:14
@squaremo  that does not solve the problem for me doing a similar use case. The problem is that the operator only checks basic metadata about the release, like the values, to determine if it needs to install.

If the dry-run gave more info about resources to create or update, maybe that could inform if we need to do anything or not?

**Comment by captncraig** [comment] 2019-01-22 02:32
Best I can find is calling for [`ReleaseStatus`](https://godoc.org/k8s.io/helm/pkg/helm#Client.ReleaseStatus) from helm. `resp.GetInfo().GetStatus().GetResources()` has a big string of text that looks to be the same as helm cli prints. Perhaps searching that for the string `==> MISSING` would handle at least this case.

**Comment by squaremo** [comment] 2019-01-22 15:07
> Short of running a full `helm upgrade` on a schedule of some kind, I feel like there are ways for things to slip through the cracks.

There are; Helm is inherently biased towards operations rather than declarations, and it is hard if not impossible to paper over the gap.

For example, the rationale behind testing for a difference in the dry-run is that if the operator called `helm upgrade` unconditionally, Helm would happily record the proliferation of no-op releases, making a nonsense of its own state. The trade-off for having a sensible record in Helm terms is some false negatives (though it can be tightened up, no doubt).

**Comment by 2opremio** [comment] 2020-01-25 15:57
@ahmadiq @captncraig Is this still a problem with the latest version of the Helm Operator?

**Comment by hiddeco** [comment] 2020-04-07 10:22
Closing as this is likely no longer an issue.

**Closed by hiddeco** 2020-04-07 10:22 UTC
Labels: bug, helm, review
