### ISSUE TITLE
Incorrect image sorting

### ISSUE THREAD

**Issue by karlmuscat** [fluxcd/flux#3417] opened 2021-02-05 07:31 UTC
**Describe the bug**

Image sorting seems to be incorrect for [reproducible builds](https://reproducible-builds.org/): 

```
WORKLOAD              CONTAINER       IMAGE                                    CREATED
test:deployment/test  test-container  xxx.dkr.ecr.eu-west-1.amazonaws.com/test
                                      '-> 1.0.0-test.98                        01 Jan 70 00:00 UTC
                                          1.0.0-test.99                        01 Jan 70 00:00 UTC
                                          2.0.0-test.98                        01 Jan 70 00:00 UTC
```
 Using `semver` filtering:
 
 ```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:*
```

**Expected behavior**

Versions follow the semver formatting, so I was expecting the ordering to be the inverse of the above.

**Additional context**

- Flux version: 1.21.1
- Kubernetes version: 1.15
- Git provider: Github
- Container registry provider: ECR

**Comment by stefanprodan** [comment] 2021-02-05 07:54
Please try `semver:^1.x-0` and see if it fixes the ordering. 

PS. The above works fine with [Flux v2 image automation](https://toolkit.fluxcd.io/guides/image-update/)

**Comment by karlmuscat** [comment] 2021-02-05 09:56
Tried it, still with the same problem. Upgrading to Flux2 is on our radar but wont happen in the short term.

**Comment by kingdonb** [comment] 2021-02-18 15:07
All indications from my reading of the sources are pointing to that this semver style is not supported in Flux v1, though it is supported in Flux v2.

Adding the image suffix in Flux v1 means your image tags will not match semver according to Flux v1. What comes after the dash indicates a prerelease (this is not supported by Flux v1, also doesn't match what you're doing according to Semver 2 spec) and alternatively, what comes after a plus indicates build metadata (which should not be considered for sorting anyway.)

Flux v1 will not be able to change the behavior of image sorting and semver since this represents a breaking change. Please consider upgrading to Flux v2; it's understandable if it's due to time concerns or production or other reasons you can't upgrade just now. Flux v2 is reaching feature parity and should be better for all use cases by this point, though it is still in pre-release, we would really appreciate your feedback on it since it is a total rewrite and has been redesigned with the most common unaddressed issues of Flux in mind.

We hope to make everyone happy before Flux v2 reaches "1.0" some time within the next probably several months, and if there is a technical reason or something else relating to your use case, we will be very interested to hear from you about it.

Closing, thanks for your interest and thanks for using Flux!

**Comment by karlmuscat** [comment] 2021-02-18 15:41
I beg to differ @kingdonb. According to FluxV1 documentation [(here)](https://docs.fluxcd.io/en/1.21.0/references/fluxctl/#semver), semver is perfectly supported. 

What seems to be not working as expected is when the dates for various images are identical. The above problem is also reproducible when no prerelease tags are used, and the dates are identical, ie:

```
WORKLOAD              CONTAINER       IMAGE                                    CREATED
test:deployment/test  test-container  xxx.dkr.ecr.eu-west-1.amazonaws.com/test
                                      '-> 1.0.0                                01 Jan 70 00:00 UTC
                                          1.0.1                                01 Jan 70 00:00 UTC
                                          2.0.0                                01 Jan 70 00:00 UTC
```

It seems that the sorting stops at the date field.

**Comment by kingdonb** [comment] 2021-02-19 12:53
It seems you're right, the documentation does describe some modicum of support for prerelease (though it can't be said for sure that flux will sort prerelease semver tags correctly, I know that alpha and beta come before rc for release candidate, but I doubt that information has been coded into Flux v1 and who is to say we agree on the order...)

Those tags can be ordered in Flux v2 and there is a guide for how: https://toolkit.fluxcd.io/guides/sortable-image-tags/ the supposition in the new architecture does not consider timestamps at all, in fact it does not even have access to them because they are image layer metadata, and the new Flux will avoid pulling image layers at all costs, preferring to lean on a natural sort order that has to be provided by innate string properties (eg. alphabetic order or numeric ordering) from the image tag itself.

Since you've provided another example that shows the problem manifests even with regular semver release tags, I will happily reopen this and take another look.

#548 (still open at this time) tracks the production of reproducible builds with Flux itself. This issue (#3417) tracks when reproducible builds are used in the client images.

I'd like to get a look at the image automation logs, (unfortunately in Flux it's not as straightforward to tease this out as "show the logs from the image automation and reflection controllers") – another way that Flux v2 tackles this issue more handily.

@karlmuscat There are several different semver annotations mentioned in this thread, can you confirm which tag you're using now? Is it `semver:*` or `semver:^1.x-0`

**Comment by karlmuscat** [comment] 2021-02-19 13:01
`semver:*` but both should be expected to behave the same given that the image tags in the last example do not have a prerelease part.

**Comment by kingdonb** [comment] 2021-02-19 13:15
Yes, I understand better now. Thank you for explaining with examples.

I will do a dive into the code and try to understand the way that semver and prerelease are implemented in Flux v1, and why it might fail when the image timestamps are zero. If you've already looked at the code and can understand this better than I do, some pointers would help. If you are able to reproduce this reliably (ha, of course you are...) what would help me the most is a published test case that demonstrates the issue, eg. a repository with github action that does produce and push image tags with zeroed timestamps such as these, that I can fork and use to repro the issue without trying to cobble one together myself.

Again if you actually know exactly what is wrong in the code, nothing is surer to get this issue addressed in the next release of Flux than submitting a PR that fixes this, I will review it and do my best to get it merged. I'm giving priority attention to issues that have been posted in the last 90-120 days first, but there are still over 300 issues (down from 400+) to close or transfer out from Flux v1 if they still represent issues that have not been closed in the redesigned implementation.

The next best thing I could ask, second most likely way to contribute to the resolution of this issue, would be to provide reproduction step on a silver platter, so that whoever finds and fixes the code issue can test a new build, commit their PR, check the test case, and of course then finally ring the bell 🔔 closing the issue with a merged fix and new release.

We appreciate our persistent users such as yourself and I want to reiterate that we are committed to supporting Flux v1 in maintenance mode. Thanks again for posting.

**Comment by kingdonb** [comment] 2021-02-19 13:20
If you grep your logs for `"image with zero created timestamp"` does it appear anywhere?

**Comment by kingdonb** [comment] 2021-03-17 20:28
There are a family of issue reports related to this one. In 1.22.0, we fixed an issue with sha-tagged images.

I hope to address this issue in 1.22.1 if possible. It will have a much better shot if there is an interested co-contributor who can collaborate on testing the fix with some of their own exotic use cases (or, who can suggest the changes that might be needed in a PR.)

Bearing in mind that breaking changes are off-limits, it seems that if a zero timestamp stops the processing of even semver filters, then there is a bug and it cannot be classified as anything but a bug. I'd love to be able to say that we can support users that are doing reproducible builds.

It is one of the more attractive open issues remaining in the PR / issue queue, but at this time with the backlog as large as it still remains, there are so many issues yet to close. It stands a much better chance of getting resolved if someone out there who is looking for `good-first-issue` and wants to contribute to Flux v1 in maintenance mode.

We have closed over 50% of issues and PRs since I started on the backlog in January of this year. 🎉 I will try to keep this pace and within 4 months we should see the Flux v1 issue backlog more like in the shape we'd like to see for any project.

I am confident that we will get to this, but I have to beg for some assistance once in a while.

If you have already moved on to Flux v2, or are no longer interested in solving this, please feel free to close this issue as it will serve as equally good form of documentation whether it is open or not. I will leave it open since, like I said, it looks attractive and could be a good first issue for someone that wants to cut their teeth on a Go project that is not a fast-moving target.

**Comment by kingdonb** [comment] 2021-04-15 20:21
So, I found some code that is related.

```
func (s SemverPattern) RequiresTimestamp() bool {
        return false
}
```

This `RequiresTimestamp` method is in `pkg/policy/pattern.go` in the `Pattern` interface.

From within the calculateChanges method:

```
                                if pattern.RequiresTimestamp() && (current.CreatedAt.IsZero() || latest.CreatedAt.IsZero()) {
                                        logger.Log("warning", "image with zero created timestamp", "current", fmt.Sprintf("%s (%s)", current.ID, current.CreatedAt), "latest", fmt.Sprintf("%s (%s)", latest.ID, latest.CreatedAt), "action", "skip container")
                                        continue containers
                                }
```

That all sounds right... now I've noticed that your provided example uses the `filter.fluxcd.io/chart-image` annotation, so this must be a Helm chart update. I'm not sure if that exercises the same codepaths. (It would seem not, if this failure you ran into is any indication.)

I've gone to some lengths now to try to reproduce the issue to better isolate the reason for the problem, and I'm stuck when I realized, I do not have a way to produce images with a zero timestamp.

@karlmuscat I found references to this in some build tools, like `jib`, but that's a deeper rabbit-hole than I am prepared to go down to resolve this. Can you provide a reference to some simple method for creating builds with a zero timestamp, as yours appear to have? (I apologize for the amount of time that has passed, if this issue is no longer on your radar than I can close it.)

**Comment by kingdonb** [comment] 2021-04-15 20:46
Looking for other differences, I've found that when reviewing the output of `list-images` for a chart-image vs a deployment (or anything else), there is some difference in certain circumstances.

```
$ fluxctl --k8s-fwd-ns fluxcd list-images
WORKLOAD                       CONTAINER    IMAGE                 CREATED
prod:daemonset/podinfo-prod    podinfo      stefanprodan/podinfo
                                            |   5.2.0             22 Mar 21 09:56 UTC
                                            |   latest            22 Mar 21 09:56 UTC
                                            '-> 5.1.4             02 Feb 21 14:37 UTC
                                                5.1.3             31 Jan 21 10:46 UTC
                                                5.1.2             14 Dec 20 11:27 UTC
                                                5.1.1             09 Dec 20 09:16 UTC
                                                5.1.0             08 Dec 20 15:48 UTC
                                                5.0.3             28 Oct 20 09:55 UTC
                                                5.0.2             06 Oct 20 07:03 UTC
                                                5.0.1             21 Sep 20 07:53 UTC
prod:helmrelease/podinfo-prod  chart-image  stefanprodan/podinfo
                                            |   9715769           27 Oct 18 08:52 UTC
                                            |   7181351           25 Mar 19 10:13 UTC
                                            |   2192219           18 Aug 18 11:24 UTC
                                            |   5.2.0             22 Mar 21 09:56 UTC
                                            '-> 5.1.4             02 Feb 21 14:37 UTC
                                                5.1.3             31 Jan 21 10:46 UTC
                                                5.1.2             14 Dec 20 11:27 UTC
                                                5.1.1             09 Dec 20 09:16 UTC
                                                5.1.0             08 Dec 20 15:48 UTC
                                                5.0.3             28 Oct 20 09:55 UTC
```

I was experimenting and I noticed some images with some strange looking tags, like `9715769` listed here. They do not belong at the top of the sort order, and I don't know why they only show up for chart-image and not deployment or daemonset.

This leads me to believe your issue will only be reproducible with a `chart-image` annotation, although I haven't been able to repro it myself, there should not be any difference in the output here unless a different code path is used, (and since we can see the code path in `calculateChanges` looks pretty straightforward, I guess that's a good bet. I haven't found it yet.)

**Comment by kingdonb** [comment] 2021-04-23 15:39
Closing, as I cannot repro without some help.

I will get around to reading these code paths at some point, but substantial changes are unlikely to be incorporated (unless there is clearly a bug and we can fix it without breaking anything.)

If I have a new reporter actively experiencing this issue, I'll be more than happy to reopen (or feel free to open a new/separate issue.)

Thanks for using Flux!

**Closed by kingdonb** 2021-04-23 15:39 UTC
Labels: bug, size/medium

**Comment by dirol13** [comment] 2021-06-18 08:12
Hello I can provide help with repro, contact me please.
