### ISSUE TITLE
Sync hangs with neither error nor success produced

### ISSUE THREAD

**Issue by redbaron** [fluxcd/flux#3237] opened 2020-08-07 13:21 UTC
**Describe the bug**

No changes applied to the cluster.

Inside flux container there is `kubectl apply -f -` process running, looks like it is hanging. I tried to run kubectl with same auth args from inside container and it connects and queries k8s API server without a problem, so it not a networking issue.

**To Reproduce**

It's hard to tell. Another flux instance running in the same cluster and syncing from the same git repo, but different paths, seems to work fine.

In the repo being synced there is no `.flux.yaml` file , just plain YAML files + SOPS

**Logs**

Last logs related to sync is
```
ts=2020-08-07T12:52:14.98663298Z caller=sync.go:61 component=daemon info="trying to sync git changes to the cluster" old=fe9454f118e26ce3b55f08e3ee6e9fc8e1115910 new=9c3741781d4b5ea518b0f7406250fb2500261846
ts=2020-08-07T12:52:17.607597406Z caller=sync.go:540 method=Sync cmd=apply args= count=102
```

**Additional context**

- Flux version:  1.20.1
- Kubernetes version: 1.16.8
- Git provider: github
- Container registry provider: GCR, Docker hub

**Comment by sharkymcdongles** [comment] 2020-08-07 14:43
I am encountering the same problem. I finally narrowed it down to having flux try to deploy a clusterissuer on top of the crd for clusterissuer. I tried even committing the CRDs by themselves and allowing a sync before commiting the clusterissuer. It caused the same hanging as described here. :(

**Comment by redbaron** [comment] 2020-08-07 14:52
I narrowed it down to `challenges.acme.cert-manager.io` CRD resource. Running `kubectl apply -f - --server-dry-run` locally makes kubectl spin on CPU , probably calculating a diff  for this massiv 305K YAML

**Comment by stefanprodan** [comment] 2020-08-07 14:56
Yeah it's a kubectl bug, duplicate of: #3236

**Closed by stefanprodan** 2020-08-07 14:56 UTC
Labels: blocked-needs-validation, bug
