### ISSUE TITLE
Flux has unexpected unrecoverable failure mode with k8s yaml missing "name" field

### ISSUE THREAD

**Issue by rocktavious** [fluxcd/flux#2933] opened 2020-03-24 02:56 UTC
**Describe the bug**

We commited a file to our flux repo that had this

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: &serviceName
```

which resulted in this flux error

```
flux-765685c7c6-9hrqv flux ts=2020-03-09T19:08:18.21123823Z caller=loop.go:107 component=sync-loop err="loading notes from repo: parsing nutrition-prod:deployment/: invalid service ID"
```

and after removing the file from the repo flux was still stuck on it with the above error
We then tried deleting the flux pod and letting it come up from scratch but it created the same error message.

So to fix it I had to manually move the git tag forward past the fix and kill the flux pod to get things back into a working state.

**To Reproduce**

Commit an invalid yaml specifically with a missing "name" resource and then try to recover from it

**Expected behavior**

We would expect the next commit to come after that in the repo if it adds a name to the resource the flux should move ahead and not get hungup / stuck and have to have the git tag moved forward manually and then restart flux daemon.

**Logs**

```
flux-765685c7c6-9hrqv flux ts=2020-03-09T19:08:18.21123823Z caller=loop.go:107 component=sync-loop err="loading notes from repo: parsing nutrition-prod:deployment/: invalid service ID"
```

**Additional context**

- Flux version: 1.18
- Kubernetes version: 1.11.6
- Git provider: Github

**Comment by kingdonb** [comment] 2021-02-23 15:51
While this sounds like a bug to me, I really only learned that YAML has this reference-anchor feature very recently, and I think generally speaking you might have more difficulty reproducing this class of error in Flux v2 as there is no room for ambiguity in the new design between what controller is responsible for sources, and what controller is responsible for applying them.

I'd be very surprised if a similar issue can be demonstrated in Flux v2. The new release has been rewritten from scratch, and is now announcing feature parity has been reached with Flux v1. All users are being encouraged to upgrade if it is possible, and report on any issues to explain why not (that being so, in case it was not possible to upgrade for some reason.)

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If you have a suggestion for how this can be resolved in Flux v1, I will be happy to reopen and/or review a PR, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.

**Closed by kingdonb** 2021-02-23 15:51 UTC
Labels: bug, flux2
