### ISSUE TITLE
Maintenance window and exclusions support

### ISSUE THREAD

**Issue by kammous** [fluxcd/flux#2712] opened 2019-12-24 13:33 UTC
**Describe the feature**
A user can configure maintenance windows and maintenance exclusions to control when automatic updates can and cannot occur. 

**What would the new user story look like?**

0. Application updates mustn't occur during some hours/days
1. User starts up Flux using --maintenance-windows  or --exclusions-windows flags (to be defined)
2. New commits in git branch happen out of maintenance/update windows
3. Deployments doesn't happen

**Expected behavior**
Updates occur only during maintenance windows and out of exclusions hours/days.

**Comment by 2opremio** [comment] 2020-01-10 16:43
> A user can configure maintenance windows and maintenance exclusions to control when automatic updates can and cannot occur.

I understand that you would still want Flux to keep syncing during that window, just not updating the workloads automatically.

How about simply running Flux in read-only mode during that Window? If you don't want Flux to deploy anything during the window you can simply stop it (or reduce it's replica number to 0).

How often do maintenance Windows happen?

**Comment by kammous** [comment] 2020-01-17 16:15
> I understand that you would still want Flux to keep syncing during that window, just not updating the workloads automatically.

Out of maintenance hours, Flux must not sync with git repository or Docker registry to avoid disturbing running workloads. It is like if Flux is in freeze mode or even stopped.

> How about simply running Flux in read-only mode during that Window? If you don't want Flux to deploy anything during the window you can simply stop it (or reduce its replica number to 0).

Stopping Flux by reducing its replica to 0 can be a suitable workaround but it requires a manual intervention or an external process with its RBAC config. 
It would great to have maintenance hours as a build-in feature of Flux. 

> How often do maintenance Windows happen?

Maintenance windows can be considered as a daily windows corresponding to out of working hours. For instance from 8 PM to 6 AM. It can be used to authorize updates during weekends. 
Here is example of how we can envision [maintenance windows and exclusions config](https://cloud.google.com/kubernetes-engine/docs/how-to/maintenance-windows-and-exclusions)

**Comment by phisco** [comment] 2020-06-17 08:39
+1 for this feature!

**Comment by kingdonb** [comment] 2021-02-20 00:43
You can schedule CronJob to scale the replicas of flux, it would not require any manual intervention just some additional tools that are outside of Flux. This is an interesting feature request, but as a developer I also hate it, since I lived with maintenance windows and could not deploy during production for a long time, due to restrictive IT policies that made it very hard to do my job effectively. Systems can be built with resilience characteristics such that deployments can happen many times throughout the day, this is the whole point of FluxCD org and Flagger to me.

Let DevOps people work normal working hours if yours is not a 24/7 shop, devs should not be expected to go in to work outside of normal working hours any more than your regular line workers are. Systems should be built with reliability in mind even when an upgrade takes place during business hours, schedule maintenance and roll out releases during peak production hours if those are your developers working hours, you want their full attention on the deployment and highly functioning organizations will be striving to keep deployment cycles short, so that changes can be applied in small increments and iteratively. Measure and remediate incidents. Do root cause analysis. Build better systems!

👎 from me for this feature.

**Comment by levsha** [comment] 2021-04-15 15:35
Actually, especially because no one wants to work outside of normal working hours, SREs usually want to have control when when automatic updates can and cannot occur - ideally they should be performed in normal operational hours.
Of course "in ideal word" all deployments should be 100% safe. But reality is slightly different.

As SRE I want to be able to define regular schedules like "not automatic updates from Friday morning till Monday morning" and also ad-hoc blocks like "no automatic updates during Christmas holidays".

**Comment by kingdonb** [comment] 2021-07-31 16:23
Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!

**Closed by kingdonb** 2021-07-31 16:23 UTC
Labels: enhancement, vague
