### ISSUE TITLE
Consider exposing image and commit hooks in the HTTP API

### ISSUE THREAD

**Issue by brantb** [fluxcd/flux#1496] opened 2018-11-06 19:09 UTC
We'd like to reduce the amount of time it takes for image or git repository changes to be picked up by Flux using webhooks to notify Flux of updates, but the hooks to do so are only exposed to the `Upstream` API.

It's possible to partially work around this for git updates by calling the `/api/flux/v9/update-manifests` endpoint (like `fluxctl sync`) and discarding the result, but this is wasteful since that API was designed to start a background job and report on progress.

**Comment by warmfusion** [comment] 2019-05-20 13:14
Is this related to https://github.com/weaveworks/flux/issues/1128 ?

**Comment by 2opremio** [comment] 2019-06-25 16:51
I would say it's a duplicate of #1128

**Comment by kingdonb** [comment] 2021-04-24 17:05
The flux-recv project has been upgraded in Flux v2 to a first-class part of Flux, the notification-controller.

I will close the issue for now as it is stale. Flux v1 remains in maintenance mode. I added details about this use case to #1128 and there are loads of additional docs in the Flux v2 https://toolkit.fluxcd.io project page.

We can provide support to Flux v1 users especially with respect to migrating to the new Flux version, Flux v2, which has some breaking changes but is also a total rewrite and also brings many improvements. I'm closing the issue but you are most welcome to write back on this issue, or open another issue. Thanks for using Flux.

**Closed by kingdonb** 2021-04-24 17:05 UTC
Labels: enhancement, help wanted
