### ISSUE TITLE
Deployment out of Sync Helm Release stuck in Pending-Upgrade

### ISSUE THREAD

**Issue by OliverLeighC** [fluxcd/flux#3134] opened 2020-06-12 21:29 UTC
**Describe the bug**

Flux auto updates the helm release to the newest image tag (as usual) but the deployment resource gets stuck on the out dated image tag. If you run `fluxctl list-images` you'll see the helm release pointing to the correct version, but the deployment is pointed to an outdated version. The helm release is marked as pending-upgrade but nothing happens no matter how long you wait. 

Running fluxctl sync doesn't help. The flux logs are normal, it always says there are no changes on the helm release. I have also tried doing a flux release on the deployment but it says the repo hadn't changed which is true because the git repo is up to date with the helm release, it's the deployment that is out of sync. 

The only way we've been able to get them back in sync is to delete both the deployment and helm release and then run fluxctl sync and wait for them to start back up.

**To Reproduce**

Steps to reproduce the behaviour:

Unfortunately I don't have a way to reproduce it because it happens somewhat randomly, and I haven't been able to ever replicate it on purpose. Here is our flux install though: 

```
helm upgrade -i flux fluxcd/flux --wait \
--namespace flux \
--set git.url=git@github.com:RockCreekGroup/kubernetes-gitops \
--set git.path="$FLUXPATHS" \
--set git.branch="$GITBRANCH" \
--set-file ssh.known_hosts=$known_hosts_path
```

FluxPaths looks something like this `release/<env name>`
Gitbranch is either master or production

**Expected behavior**

When flux updates the image tag in the helm release and the helm release is updated in the cluster, the deployment should update to that tag as well.

**Additional context**

- Flux version: flux-1.2.0  
- Helm Operator: helm-operator-0.7.0
- Kubernetes version: 1.15
- Git provider: Github
- Container registry provider: AWS
- Helm Version: 3

**Comment by Xyaren** [comment] 2021-01-22 11:12
I experience the same Issue that has started due to fkux not being to do something with the image in the deployment due to rate limiting on the docker registry side.
Now I am stuck with the helmrelease in "pending-upgrade"

**Comment by kingdonb** [comment] 2021-02-19 16:45
Is anyone able to provide something closer to steps that reproduce? It will be hard to address this without something concrete.

Apologies about the length of time that has elapsed since your inquiry. As efforts have been focused on Flux v2, I've recently joined the team to focus on Flux v1 issues, and we have developed a support policy page with references to how community works in our new architecture for Flux v2, different ways to meet us for help. If you've been following our development efforts then of course we hope you are able to upgrade, here's more info on how to find support with that: https://fluxcd.io/support/

If this is still affecting you, I will be happy to troubleshoot with you either here, or in the #flux slack channel on CNCF. But I'm going to need an active repro that I can probe with further questions.

**Comment by OliverLeighC** [comment] 2021-02-19 16:59
This was solved for our team, it seemed like the helm operator was frequently crashing which would cause this issue because it was always evicted. Honestly I'm not sure how it was solved, it could be when we updated our kubernetes or increased resource provisions. 

For @Xyaren this issue might help (rate limiting) https://github.com/fluxcd/flux/issues/2845#issuecomment-763825533

**Comment by kingdonb** [comment] 2021-02-19 22:06
That's good news. Since the original report is gone, I'll close this issue.

@Xyaren if you are still having issues, welcome to open a separate report and provide details, or flag me down in #flux on CNCF slack and I can try to help.

Thanks for using Flux!

**Closed by kingdonb** 2021-02-19 22:06 UTC
Labels: blocked-needs-validation, bug
