### ISSUE TITLE
It takes a long time for HelmReleases to be applied

### ISSUE THREAD

**Issue by jan-schumacher** [fluxcd/flux#2052] opened 2019-05-16 07:50 UTC
**Describe the feature**
It would be really handy when fluxctl has a command to force new creation of missing releases. I.e.: When I do `kubectl delete hr redis` it takes a lot of time to recreate the missing releases.

**What would the new user story look like?**
As a user I would love to force create missing releases. So that when I delete an existing release I don't have to wait a long time till it's recreated.
A `force` option on fluxctl sync command would be enough to fit the need.
`fluxtctl sync --force` or `fluxtctl sync --force-create`

**Expected behavior**
When I use `fluxtctl sync --force` or `fluxtctl sync --force-create` all missing releases will be created immediately.

**Comment by 2opremio** [comment] 2019-05-16 08:09
What do you mean by _missing release_?

**Comment by jan-schumacher** [comment] 2019-05-16 08:17
> What do you mean by _missing release_?

Well, when I delete a release manually with `kubectl delete hr` it is "missing" from there on for reasons. And in most of our cases we would love to immediately force flux to run the recreation process because the release is missing then.

**Comment by 2opremio** [comment] 2019-05-16 08:21
Ahh, in Flux's terminology that's a workload.

**Comment by hiddeco** [comment] 2019-05-16 08:33
What extra functionality would the `--force` flag on `fluxctl sync` offer? If you would do a `fluxctl sync` at the moment it would already create those resources instantly (and the Helm operator would act on the creation shortly after).

**Comment by jan-schumacher** [comment] 2019-05-16 11:12
> What extra functionality would the `--force` flag on `fluxctl sync` offer? If you would do a `fluxctl sync` at the moment it would already create those resources instantly (and the Helm operator would act on the creation shortly after).

No, it does not. We tried that several times.

**Comment by hiddeco** [comment] 2019-05-16 11:19
`fluxctl sync` will not say the sync was successful before it has applied all resources to the cluster, so the `HelmReleases` must be created (or we have bigger problems).

I have a suspicion the Helm operator does not react as fast as you'd like. Can you share the logs from the operator while you're doing a `fluxctl sync`?

**Comment by jan-schumacher** [comment] 2019-05-16 11:56
I will share them later, I have a meeting, but what I can say is that it takes up to 10 minutes till recreation. Even when I do fluxctl sync

**Comment by 2opremio** [comment] 2019-05-28 12:05
Related #1128

**Comment by semyonslepov** [comment] 2019-08-20 10:31
I think the initial problem here is that there is no way to force the Helm operator. You can force flux to sync the HRs but can't force Helm operator to start its "watch changes and apply if any" right now. I also hit this on our setup (not critical yet but it would be nice to have a similar functionality on the operator side).

**Comment by JVMartin** [comment] 2019-11-22 17:51
I can confirm, this is an issue not just for Helm releases, but for *any* Kubernetes resources.

Say that you have a secret managed with Flux.

You can do this:
```
> kubectl delete secret mysecret
secret "mysecet" deleted
> fluxctl sync
Synchronizing with git@git.trendcapital.io:trend-capital/flux.git
Revision of master to apply is a1e0c48
Waiting for a1e0c48 to be applied ...
Done.
> kubectl get secret
No resources found in default namespace.
> kubectl get secret
No resources found in default namespace.
> kubectl get secret
No resources found in default namespace.
> kubectl get secret
No resources found in default namespace.
> kubectl get secret
No resources found in default namespace.
> kubectl get secret
No resources found in default namespace.
> kubectl get secret
No resources found in default namespace.
> fluxctl sync
Synchronizing with git@git.trendcapital.io:trend-capital/flux.git
Revision of master to apply is a1e0c48
Waiting for a1e0c48 to be applied ...
Done.
> kubectl get secret
No resources found in default namespace.
> kubectl get secret
No resources found in default namespace.
> kubectl get secret
No resources found in default namespace.
> kubectl get secret
No resources found in default namespace.
> kubectl get secret
No resources found in default namespace.
```

It can take hours or days for the resource to re-appear.

What's going on here?

**Comment by 2opremio** [comment] 2019-11-22 18:33
@JVMartin can you create a separate issue and share extra information (environment, Flux version, flux logs etc ...)? I doubt that what you are experiencing is related to the current issue.

Also, without further context it's hard to conclude whether a secret is expected to appear in the cluster through flux.

**Comment by JVMartin** [comment] 2019-11-22 19:26
@2opremio Exactly like @jan-schumacher said, after a few minutes / hours, Flux *finally* notices the secret is missing, re-creates it, and all is well. With 0 intervention. It just takes a long time. This is true of ALL resources, not just HelmReleases, not just Secrets. Deplyoments, services, you name it. It seems like Flux should immediately notice when something has been deleted and re-create it, but it doesn't. I'll create a new issue and add more details when I get a chance.

**Comment by JVMartin** [comment] 2019-11-22 19:27
You don't have to take my word for it. Just delete any resource from your cluster, call `flux sync`, and you'll see that it doesn't come back.

**Comment by hiddeco** [comment] 2019-11-22 19:40
`fluxctl sync` only syncs a revision if it has not applied that revision yet.

Are you saying that the reconciliation loop that happens every `--sync-interval` does not put the resource back? Or is the `--sync-interval` in your case set to a very high value? As that would explain why it would take 'hours'.

**Comment by kingdonb** [comment] 2021-02-26 17:03
This is hopefully resolved in Flux v2 by adding the `reconcile` verb and `--with-source` flags to the `flux` cli.

The Flux v1 CLI is not very full-featured because the Flux v1 API doesn't expose many features. The rebuilt from scratch Flux v2 has put a great deal of thought into the design of Flux's conversations between a git repository and a reconciler, and made it more open so the CLI can implement observability for all of the richness of these interactions.

Flux v1 is in maintenance mode now, and is not adding any new features unless they are critical.

As Flux contrib efforts have been focused on Flux v2, the Flux project has moved to a new repo, [fluxcd/flux2](/fluxcd/flux2)

In the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode, and respecting you may have moved on already, I will go ahead and close out this issue for now.

**Closed by kingdonb** 2021-02-26 17:03 UTC
Labels: enhancement
