### ISSUE TITLE
Return meaningful error when something went wrong

### ISSUE THREAD

**Issue by srikantheee84** [fluxcd/flux#1223] opened 2018-07-11 23:43 UTC
I'm unable to update new images pushed to private docker registry

Here is the list of images:

```
 $ fluxctl list-images -n flux --controller=deployment/xxx
CONTROLLER               CONTAINER  IMAGE                                  CREATED
flux:deployment/xxxx  xxxx    xxxx  
                                    |   8.2.0-snapshot                     11 Jul 18 15:49 UTC
                                    '-> 8.1.0-snapshot-new                 19 Apr 18 18:03 UTC
```
Here is the error:

```
$ fluxctl release --controller=flux:deployment/xxxx --user=xxxx --message="New version" --update-all-images
Submitting release ...
Error: Traceback (most recent call last):
  File "kubeyaml.py", line 139, in <module>
  File "kubeyaml.py", line 134, in main
  File "kubeyaml.py", line 48, in apply_to_yaml
  File "kubeyaml.py", line 54, in update_image
  File "site-packages/ruamel/yaml/main.py", line 296, in load_all
  File "site-packages/ruamel/yaml/constructor.py", line 97, in get_data
  File "site-packages/ruamel/yaml/composer.py", line 65, in get_node
  File "site-packages/ruamel/yaml/composer.py", line 96, in compose_document
  File "site-packages/ruamel/yaml/composer.py", line 132, in compose_node
  File "site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
  File "site-packages/ruamel/yaml/composer.py", line 132, in compose_node
  File "site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
  File "site-packages/ruamel/yaml/composer.py", line 132, in compose_node
  File "site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
  File "site-packages/ruamel/yaml/composer.py", line 132, in compose_node
  File "site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
  File "site-packages/ruamel/yaml/composer.py", line 130, in compose_node
  File "site-packages/ruamel/yaml/composer.py", line 163, in compose_sequence_node
  File "site-packages/ruamel/yaml/composer.py", line 132, in compose_node
  File "site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
  File "site-packages/ruamel/yaml/composer.py", line 130, in compose_node
  File "site-packages/ruamel/yaml/composer.py", line 163, in compose_sequence_node
  File "site-packages/ruamel/yaml/composer.py", line 132, in compose_node
  File "site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
  File "site-packages/ruamel/yaml/composer.py", line 106, in compose_node
  File "site-packages/ruamel/yaml/parser.py", line 144, in check_event
  File "site-packages/ruamel/yaml/parser.py", line 572, in parse_block_mapping_value
  File "site-packages/ruamel/yaml/scanner.py", line 1620, in check_token
  File "site-packages/ruamel/yaml/scanner.py", line 1662, in _gather_comments
  File "site-packages/ruamel/yaml/scanner.py", line 310, in fetch_more_tokens
ruamel.yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<stdin>", line 46, column 22
Failed to execute script kubeyaml
Run 'fluxctl release --help' for usage.
```

We are also using private bitbucket repository

**Comment by srikantheee84** [comment] 2018-07-12 22:01
I'm not sure why error message looks like some yaml parsing issue (spaces instead of tab)

```
found character '\t' that cannot start any token
  in "<stdin>", line 46, column 22
Failed to execute script kubeyaml
```

**Comment by squaremo** [comment] 2018-07-19 09:15
Ugh, that is a terrible error message isn't it -- sorry about that. Are you able to post the YAML file for which it's failing (sanitised if necessary)?

**Comment by kingdonb** [comment] 2021-04-07 20:38
Closing, cannot reproduce the issue without the YAML that triggered the issue.

The image automation in Flux v2 is all go, no python, so error messages like this should not be possible anymore 👍

**Closed by kingdonb** 2021-04-07 20:38 UTC
Labels: UX, help wanted
