### ISSUE TITLE
GCR image format not supported?

### ISSUE THREAD

**Issue by Jonathan34** [fluxcd/flux#2443] opened 2019-09-10 17:54 UTC
**Describe the bug**
I have used skaffold to deploy my image for now and wanted to setup flux.
my deployments have an image that looks like this:
`gcr.io/project_id/image_name:tag@sha256:c90d11…`

and I get the following error messages from flux
`expected image name as either <image>:<tag> or just <image>: invalid image ID`

in the k8s manifests, i set the image to `image_name:tag`

**Expected behavior**
No message, format is supported.

**Comment by Jonathan34** [comment] 2019-09-10 22:24
ok I've set the deployment to `gcr.io/project/image:tag` and flux is happy again.
guess if you can close this if you want

**Comment by hiddeco** [comment] 2019-09-11 09:14
Duplicate of #885, has been worked on in in #2162 but shows signs of rot.

**Closed by hiddeco** 2019-09-11 09:14 UTC
Labels: blocked-needs-validation, bug
