### ISSUE TITLE
Real git error is not shown in the fluxd pod logs

### ISSUE THREAD

**Issue by bzon** [fluxcd/flux#1590] opened 2018-12-06 16:08 UTC
I just encountered an issue today with fluxd pod throwing the error `err="git repo not ready: git clone --mirror: fatal: Could not read from remote repository."`. Running fluxctl actions like `fluxctl sync` also shows the same error.

I was able to find the problem after performing a manual git clone inside the fluxd pod. It is throwing the usual corrupted ssh known hosts warning and I just had to renew the known host config map to fix the problem.

Can we have the fluxd logs show the real git error instead of just saying `git repo not ready` so it can be much easier to troubleshoot?

**Comment by brunowego** [comment] 2019-08-29 15:36
In my case, the issue is with NGINX Ingress, after expose port 22, everything works fine:

```sh
helm get --all nginx-ingress values > ./current-values.yaml
```

```sh
cat << EOF | helm upgrade nginx-ingress stable/nginx-ingress -f ./current-values.yaml -f -
tcp:
  22: gitlab/gitlab-ce-gitlab-shell:22
EOF
```

```sh
rm ./current-values.yaml
```

**Comment by kingdonb** [comment] 2021-04-24 16:20
I don't think this is likely to get fixed in Flux v1, but I would like to be sure that Flux v2 "pareto-dominates" Flux v1

That is, if there are host-key issues that can be present in Flux v2, it should be better in every way. I'm not completely sure how this is handled now, (and that's a sign that we might need better documentation about it, so I'm going to keep this issue at least until I can cite docs about how it works now, or otherwise confirm for myself that Flux v2 users no longer suffer with this issue in the same ways.)

Thanks for reporting this. Flux v2 is now incubating in the CNCF and is rapidly approaching a GA release.

All users are encouraged to upgrade.

**Closed** 2021-07-31 15:56 UTC
Labels: enhancement, flux2
