### ISSUE TITLE
Semver filter for prereleases

### ISSUE THREAD

**Issue by karlmuscat** [fluxcd/flux#3413] opened 2021-02-02 21:26 UTC
Following the filtering mechanism specified [here](https://docs.fluxcd.io/en/1.20.2/references/fluxctl/#semver), is there a way how to create a filter that picks up all the versions with a particular label? Assuming there are 3 image:

```
1.0.0-alpha.1
1.0.1-alpha.1
1.0.0-beta.1
```

What would be the filter to pick up only the 2 alpha versions, and ignore the beta one? `semver:*-alpha*` ?

**Comment by kingdonb** [comment] 2021-02-12 13:07
Possible duplicate of #3417

**Comment by karlmuscat** [comment] 2021-02-12 13:12
This issue is to understand filtering capabilities of prereleases, and whether they are supported. #3417 is describing sorting problems, not filtering.

**Comment by kingdonb** [comment] 2021-02-12 13:25
I don't exactly know the answer, but I will research this and get back to you. My understanding of the semver, glob, and regexp support in Flux v1 is based on experimentation more than documentation or reading of the source code.

If you have an example of a public image registry that I can test against, I can get you the answer much faster. My go-to tool for analyzing which version filters work in Flux v1 is Weave Cloud, and from a bit of trial and error there I got the idea that semver does not support a suffix in Flux v1 – my test repo is kube-state-metrics.

<img width="798" alt="Screen Shot 2021-02-12 at 8 24 30 AM" src="https://user-images.githubusercontent.com/3286998/107773506-c01b1400-6d0b-11eb-8769-a47da8b5b33a.png">

A working filter for example is `1` which accepts any 1.x.x or `1.9`, `1.8` which limits to only images in the minor range given.

This behavior is supported in Flux v2, according to those docs which show some more flexible uses of the new semver policies:

https://github.com/fluxcd/flux2/blob/42011d028e09112440ae26be3d3b32a9e2f1a6de/docs/guides/image-update.md#configure-image-scanning

**Comment by kingdonb** [comment] 2021-02-12 22:14
Since the answer appears to be, no it is not supported, I think this can be closed. It is inadvisable to duplicate the efforts already completed in Flux v2, and moreover breaking changes are not possible while Flux v1 is in maintenance mode.

If you find the need of your use case is not met in Flux v2, please open a discussion or issue report in fluxcd/flux2. If you are not able to upgrade to Flux 2, we are interested to know more about what blocks your upgrade. But as for Flux v1, a change in the behavior of semver filters would be difficult to implement without breaking anything, as it represents a behavior change.

**Closed by kingdonb** 2021-02-12 22:14 UTC

**Comment by vchirikov** [comment] 2022-06-29 07:55
It's very sad that we can't filter by suffix
![image](https://user-images.githubusercontent.com/40987940/176382747-71c7837b-e934-455c-8490-afb4190e852b.png)

https://github.com/Masterminds/semver/issues/137

@kingdonb can we have something to filter by prerelease suffix? maybe regex or something

**Comment by kingdonb** [comment] 2022-07-05 13:32
The policy described will work on Flux v2 👍 , this is the Flux v1 repo

I was surprised at first to learn that filterTags and a semver policy can be used together, but it's true. In this case where you want the downstream to receive releases **only when** they are marked with a prerelease indicator, say you have features that are built on the edge channel and they need to maintain access to those features. This is a good example and it would make a great addition to the docs, if you want to send it as a PR 👍
