### ISSUE TITLE
Fluxctl sync fails if git hash collision

### ISSUE THREAD

**Issue by neubieser** [fluxcd/flux#3322] opened 2020-10-06 17:53 UTC
If you have 2 commits matching the first 7 characters of the hash, fluxctl sync will fail.

relevant line of code: https://github.com/fluxcd/flux/blob/master/cmd/fluxctl/sync_cmd.go#L75

**Comment by kingdonb** [comment] 2021-02-12 22:43
This looks like it could be a valid report, passing the first 7 characters into `awaitSync` might match more than one commit and could fail in surprising ways. I have not validated with a reproduction but 

Do you have a suggestion or any inclination to submit a PR that might fix this issue, @neubieser ?

(Did you actually manage to get one of these errors in your repo, so you can say something else about how it fails? I would probably go out and buy a lottery ticket, I have only seen that happen in my own repos about once that I can remember.)

**Comment by RaphaelKimmig** [comment] 2021-06-12 05:40
Not really helpful, but with about 19000 commits you'll have a 50% chance of a short hash collision.

**Comment by kingdonb** [comment] 2021-07-29 14:32
Closing in favor of #3517 (duplicate of this issue) which adds some color and includes the error messages.

I think we can probably address in the next MINOR release of Flux, v1.24.0.

**Closed by kingdonb** 2021-07-29 14:32 UTC
Labels: bug
