### ISSUE TITLE
There is no way to have Flux automated images in Helm subcharts with multiple containers

### ISSUE THREAD

**Issue by svinther** [fluxcd/flux#1629] opened 2019-01-03 13:24 UTC
The Helm convention for specifying values for subcharts is like

```
subchart:
  container1:
    image:
    tag:
  container2:
    image:
    tag:
```

But Flux does not recognize image spec structures on any sublevel of the values.yaml

Same problem for nested subcharts with only 1 container in the subchart, as the Helm convention is

```
subchart1:
  subchart2:
    image:
    tag:
```

**Comment by stefanprodan** [comment] 2019-02-28 09:45
Duplicate of #1262

**Comment by timwebster9** [comment] 2019-03-01 18:43
I'm slightly confused - doesn't [this](https://github.com/weaveworks/flux/blob/master/site/helm-integration.md#upgrading-images-in-a-helmrelease-using-flux) say it's supported at least partially:
```
values:
  persistent: true

  # image that will be labeled "chart-image"
  image: repo/image1:version

  subsystem:
    # image that will be labeled "subsystem"
    image:
      repository: repo/image2
      tag: version
      imagePullPolicy: IfNotPresent
    port: 4040
```
Having said that, I'm trying something similar and can't seem to get it to work...

**Comment by stefanprodan** [comment] 2019-03-01 18:47
Can you post your HelmRelease file? Maybe the annotations don't match

**Comment by timwebster9** [comment] 2019-03-01 18:48
@stefanprodan https://github.com/hmcts/cnp-flux-config/blob/master/k8s/aat/software-engineering/cmc-pdf-service/cmc-pdf-service.yaml

**Comment by stefanprodan** [comment] 2019-03-01 19:02
If you remove the the tag filter does it work? Make sure you have an image that's newer than `pr-73`.

**Comment by timwebster9** [comment] 2019-03-01 19:08
yes it definitely works with and without the tag filter.  I guess what I mean is it seems to be _**ignoring**_ the tag filter.

`pr-73` is the newest image (which Weave automatically deployed), but I want images tagged with `latest*`.

I realise this is probably a different issue.  I'm happy to open a new one....

**Comment by stefanprodan** [comment] 2019-03-01 19:24
If you push `pr-74` and add this filter `glob:pr-*` it should work.

**Comment by stefanprodan** [comment] 2019-03-01 19:26
If you want a different image older than the current one, set it yourself in values and change the annotation to match it.

**Comment by stefanprodan** [comment] 2019-03-01 19:40
@timwebster9 Flux doesn't work with `latest` or any fixed tags. You have to push unique tags on each build for Flux automation to detect changes. Best is to use semver or git SHA as the image tag.

**Comment by timwebster9** [comment] 2019-03-01 19:59
@stefanprodan yeah I realise that - the plan was to append a build ID from ACR to latest (e.g. `latest-db5`).  Are you saying it won't work at all if the tag is prefixed with `latest`?  It's no problem for us to change the tag to something else...

Also do I have the 'container' name correct in the filter annotation?  The name of the sub-chart is `java`, and I've set the filter tag to `flux.weave.works/tag.java`

**Comment by stefanprodan** [comment] 2019-03-01 20:04
With this annotation `flux.weave.works/tag.java glob:latest-*` if you push an image with the `latest-ID` tag it will work.

**Comment by timwebster9** [comment] 2019-03-01 20:05
I just pushed an image tagged `latest-asfsdf` and it picked it up with no other changes.

I guess what I've learnt is it won't automatically deploy `latest` even if it satisfies the glob pattern..?

**Comment by stefanprodan** [comment] 2019-03-01 20:12
It will if it's newer than the image running in the cluster. When not using sem ver, Flux looks at image layer timestamp.

**Comment by timwebster9** [comment] 2019-03-01 20:19
So let me get this straight - the glob pattern filter will be ignored if there aren't newer images than the current one that match it, even if the current image doesn't match it?

**Comment by hiddeco** [comment] 2019-10-09 14:56
> So let me get this straight - the glob pattern filter will be ignored if there aren't newer images than the current one that match it, even if the current image doesn't match it?

If the current tag does not match the configured pattern it is impossible for Flux to make an accurate decision about what it should do or how the image relates to one of the tags that matches the pattern, so it won't update and let a human decide.

---

Configuring automatic images updates of subcharts is now be possible by using [YAML dot notation annotations](https://docs.fluxcd.io/en/stable/references/helm-operator-integration.html#annotations) to map the image value paths.

**Closed by hiddeco** 2019-10-09 14:56 UTC
Labels: enhancement, helm
