### ISSUE TITLE
Invalid revision range during fluxctl release

### ISSUE THREAD

**Issue by awh** [fluxcd/flux#859] opened 2017-12-01 10:06 UTC
I just received this whilst releasing to WC production:

```Commit pushed:    079c2ba
== Error ==

Internal error: fatal: Invalid revision range flux-sync-prod..079c2ba054a0bc7e22d8e79ee734cdd2913ed2c7

We don't have a specific help message for the error above.

It would help us remedy this if you log an issue at

    https://github.com/weaveworks/flux/issues

saying what you were doing when you saw this, and quoting the message
at the top.
```

Everything seems to have worked nevertheless, including the sync tag move.

**Comment by squaremo** [comment] 2017-12-01 10:41
Interesting! That revision certainly exists in the upstream repo (as does the tag, which right now points at the revision). My guess is that it was during the "event collation" stage of the sync -- when it's looking at all the commits since last sync to figure out what happened. As far as I can tell, any errors there result in an early return. So the surprising bit is that the whole thing succeeded in effect.

**Comment by squaremo** [comment] 2017-12-01 15:04
Here's the log entry:

```
{"log":"ts=2017-12-01T09:47:49.496506951Z caller=logging.go:85 component=upstream method=SyncStatus error=\"fatal: Invalid revision range flux-sync-prod..079c2ba054a0bc7e22d8e79ee734cdd2913ed2c7\"\n", ...}
```

It was SyncStatus that returned the error -- `fluxctl release` calls it after the release job has succeeded, to be able to report when the cluster has been synced. But I guess there is a race between the commit being pulled from upstream, and `fluxctl release` asking for it.

**Comment by squaremo** [comment] 2017-12-01 15:12
A bit more information on how this can happen (I am speculating in parts):

 1. Someone calls `fluxctl release`
 2. The daemon creates a job and queues it, reporting the job ID back to `fluxctl`
 3. `fluxctl` keeps asking about the job, and the daemon replies with its status, until ..
 4. the job completes, the commit is pushed upstream, and the daemon responds with a success status including the commit ID
 5. now `fluxctl` switches to asking the daemon whether it has sync'ed to that commit yet, via the `SyncStatus` API
 6. straight after finishing the job, the daemon pulls from upstream and applies everything; now it will report that it's sync'd to the commit in question

The race happens between 5 and 6 -- you can ask about the commit before the daemon has pulled it from upstream.

**Comment by squaremo** [comment] 2018-06-05 12:59
The git syncing has been rewritten since this, so we should check if it's still a problem.

**Comment by varac** [comment] 2020-06-08 21:04
> The git syncing has been rewritten since this, so we should check if it's still a problem.

flux still can't handle rewritten git history/force pushes, see https://github.com/fluxcd/flux/issues/696#issuecomment-636201707

**Comment by kingdonb** [comment] 2021-02-19 16:57
Closing as this seems to be a duplicate of #696. The issue is still open there and references several other reports that appear to be similar or exactly the same.

I will close this issue as duplicate. Follow #696 for updates.

**Closed by kingdonb** 2021-02-19 16:57 UTC
Labels: review
