### ISSUE TITLE
Flux 1.21.0 prints Git repo credentials to logs

### ISSUE THREAD

**Issue by cochiseruhulessin** [fluxcd/flux#3330] opened 2020-10-12 21:57 UTC
**Describe the bug**

The logs contain the username and password when using Git with the HTTPS protocol.

**To Reproduce**

1. Install Flux 1.21.0
2. Configure it with the `--git-url` argument set to a Git repository with username and credentials, e.g. `https://username:credentials@gitlab.com/my/repo`
3. Ensure that Flux cloning the repository causes an error. In our case it was the firewall and later the proxy blocking the egress HTTP request.

**Expected behavior**

Logs do not contain the credentials.

**Logs**

```
ts=2020-10-12T21:49:48.179545613Z caller=sync.go:51 component=daemon warning="failed to load last-synced resources. sync event may be inaccurate" err="git repo not ready: git clone --mirror: running git command: git [clone --mirror https://cochise.ruhulessin:<REDACTED>@<REDACTED> /tmp/flux-gitclone573478643]: context deadline exceeded"
```

**Additional context**

- Flux version: 1.21.0
- Kubernetes version: 1.16
- Git provider: GitLab
- Container registry provider: GCR

**Comment by kingdonb** [comment] 2021-02-12 23:09
Is this a simple password, or one with special characters that have been URL escaped in the redacted portion?

Might be duplicate of #3339

**Comment by kingdonb** [comment] 2021-08-02 15:38
I am closing this as a duplicate of #3339 – however I can't unfortunately see this as likely being fixed in Flux v1.

Flux v1 is formally superseded, since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!

**Closed by kingdonb** 2021-08-02 15:38 UTC
Labels: blocked-needs-validation, bug
