### ISSUE TITLE
Support Helm v3

### ISSUE THREAD

**Issue by donifer** [fluxcd/flux#2611] opened 2019-11-14 02:38 UTC
**Describe the feature**
Helm v3 got released but can't find in the docs if it's compatible or not. I was not really expecting to find anything since it just got released a few hours ago. But wanted to open an issue to at least keep track of it.

**Expected behavior**
Works with helm v3.

**Comment by stefanprodan** [comment] 2019-11-14 09:01
Duplicate of https://github.com/fluxcd/helm-operator/issues/8

**Closed by stefanprodan** 2019-11-14 09:01 UTC
Labels: blocked-needs-validation, enhancement
