### ISSUE TITLE
Flux does not change manually edited resources

### ISSUE THREAD

**Issue by axelgobletbdr** [fluxcd/flux#3313] opened 2020-10-01 10:16 UTC
**Describe the bug**

When manually editing a resource inside the cluster, using e.g. `kubectl edit` or `kubectl patch`, Flux will not change the resource spec back to the state of the git repository. For me this happens when adding an extra container manually to a deployment. I feel that flux should correct this, such that cluster state is always equal to repo state. It does correct it when deleting a deployed resource.

**To Reproduce**

Steps to reproduce the behaviour:

1. Provide Flux install instructions

Fork the [flux getting started repo](https://github.com/fluxcd/flux-get-started) to your own github.

Install flux on minikube using the below script. Do not forget to change your user in the script and edit the fluxd args stated in the comments in the script. Lastly, add the ssh key to the forked repo as described [here](https://docs.fluxcd.io/en/latest/tutorials/get-started/#giving-write-access).

```
#!/bin/bash

set -e

# cluster
minikube start --cni=calico --memory=10000 --cpus=4 --network-plugin=cni

# flux
sudo snap install fluxctl --classic
kubectl create ns flux
# replace with your own github user
export GHUSER="axelgobletbdr"
fluxctl install \
  --git-user=${GHUSER} \
  --git-email=${GHUSER}@users.noreply.github.com \
  --git-url=git@github.com:${GHUSER}/flux-get-started \
  --git-path=namespaces,workloads \
  --namespace=flux | kubectl apply -f -
# add the following args to flux deployment:
# --sync-garbage-collection
# --manifest-generation=true
```

2. Provide a GitHub repository with Kubernetes manifests

Fork the [flux getting started repo](https://github.com/fluxcd/flux-get-started) to your own github.

3. Apply manual edits

Run `kubectl edit deploy podinfo -n demo` and add the following container to the container list:
```
- image: nginx
  name: nginx
```

Wait a few minutes until flux does the sync. Inspect the deployment and see that the old state is not re-applied. In the last line of the logs below you can see the flux sync trigger, and that the deployment should be "configured"

The same happens when Running `kubectl patch deploy podinfo -p "$(cat patch.yaml)"` where `patch.yaml` is

```
spec:
  template:
    spec:
      containers:
      - image: nginx
        name: nginx
```

**Expected behavior**

Flux will eventually change the edited deployment back to the state shown in the repo

**Logs**

If applicable, please provide logs of `fluxd`. In a standard stand-alone installation of Flux, you'd get this by running `kubectl logs deploy/flux  -n flux`.

```
ts=2020-10-01T10:08:03.517059843Z caller=main.go:259 version=1.20.2
ts=2020-10-01T10:08:03.517102597Z caller=main.go:412 msg="using kube config: \"/root/.kube/config\" to connect to the cluster"
ts=2020-10-01T10:08:03.535209639Z caller=main.go:492 component=cluster identity=/etc/fluxd/ssh/identity
ts=2020-10-01T10:08:03.535249336Z caller=main.go:493 component=cluster identity.pub="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCgg5gAHODxOi0pUzzYUXTEks+RbgJzVkRJgSWjMHcNCXn5GVXq8iqkr4ekacaDsAyKSKXNx74rYP0TVaCezy/R9TyRvxxIv4vv+/kDYyrhZdZwfI19BB8GgDaASqDZXws+wafpkg6TDsc3JipFDsLCOSpEznHxuwqfSMYncTyQpqrdeyCQgGh6ofBnqDv4ELEmyjJSvY3Wjact5hxF3QzsggDiadLOePUesLkGELYQjRknXZDiBBoyd0qy67WeDnSesS5X2SUJQ2Z6c06EnpaifT+16/+OmCGH+H2jdBbFK8OgkPaoS0p6a396JsEV9oSOpyXxE60h7DaN5/WC1NuHOdZivNb3fpbo3Dd5CbxgLP9wTjL9eKdxpjNlUnNc1qILpMzpLrFoitrEtmKXKkqOUb7rOpT0kw2zETpsNYLEL1H99l3HDZHXPVHsXqGjC2pOk8EaXYpww5hw3/0jjs5pcXU5TnNcx2jNZ9hmb75PpCeWaen+06Kd7bSm86rgKL8= root@flux-59c9b9c48c-m2rgd"
ts=2020-10-01T10:08:03.535273637Z caller=main.go:498 host=https://10.96.0.1:443 version=kubernetes-v1.19.0
ts=2020-10-01T10:08:03.535337196Z caller=main.go:510 kubectl=/usr/local/bin/kubectl
ts=2020-10-01T10:08:03.53611073Z caller=main.go:527 ping=true
ts=2020-10-01T10:08:03.537018326Z caller=main.go:666 url=ssh://git@github.com/axelgobletbdr/flux-get-started user=axelgobletbdr email=axelgobletbdr@users.noreply.github.com signing-key= verify-signatures-mode=none sync-tag=flux state=git readonly=false registry-disable-scanning=false notes-ref=flux set-author=false git-secret=false sops=false
ts=2020-10-01T10:08:03.537053961Z caller=main.go:772 upstream="no upstream URL given"
ts=2020-10-01T10:08:03.537123035Z caller=main.go:803 metrics-addr=:3031
ts=2020-10-01T10:08:03.537740173Z caller=sync.go:51 component=daemon warning="failed to load last-synced resources. sync event may be inaccurate" err="git repo not ready: git repo has not been cloned yet"
ts=2020-10-01T10:08:03.537819474Z caller=loop.go:108 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2020-10-01T10:08:03.537836265Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-10-01T10:08:03.537846126Z caller=images.go:27 component=sync-loop msg="no automated workloads"
ts=2020-10-01T10:08:03.538400877Z caller=main.go:795 addr=:3030
ts=2020-10-01T10:08:04.12911158Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.20.1
ts=2020-10-01T10:08:05.924934154Z caller=warming.go:198 component=warmer info="refreshing image" image=calico/pod2daemon-flexvol tag_count=1048 to_update=959 of_which_refresh=959 of_which_missing=0
ts=2020-10-01T10:08:15.65395701Z caller=loop.go:134 component=sync-loop event=refreshed url=ssh://git@github.com/axelgobletbdr/flux-get-started branch=master HEAD=c4d4cfb36510c592d1e0b11ab4c5ecd39f1e2220
ts=2020-10-01T10:08:15.807355135Z caller=sync.go:61 component=daemon info="trying to sync git changes to the cluster" old=c4d4cfb36510c592d1e0b11ab4c5ecd39f1e2220 new=c4d4cfb36510c592d1e0b11ab4c5ecd39f1e2220
ts=2020-10-01T10:08:16.102382141Z caller=sync.go:540 method=Sync cmd=apply args= count=6
ts=2020-10-01T10:08:16.507113693Z caller=sync.go:606 method=Sync cmd="kubectl apply -f -" took=404.689053ms err=null output="namespace/demo unchanged\nnamespace/nginx configured\nservice/podinfo unchanged\ndeployment.apps/nginx configured\ndeployment.apps/podinfo created\nhorizontalpodautoscaler.autoscaling/podinfo unchanged"
ts=2020-10-01T10:08:20.895582751Z caller=loop.go:236 component=sync-loop state="tag flux" old=c4d4cfb36510c592d1e0b11ab4c5ecd39f1e2220 new=c4d4cfb36510c592d1e0b11ab4c5ecd39f1e2220
ts=2020-10-01T10:08:22.449527241Z caller=loop.go:134 component=sync-loop event=refreshed url=ssh://git@github.com/axelgobletbdr/flux-get-started branch=master HEAD=c4d4cfb36510c592d1e0b11ab4c5ecd39f1e2220
ts=2020-10-01T10:08:27.51680561Z caller=rate_limiter.go:74 component=ratelimiter info="reducing rate limit" host=index.docker.io limit=25.00
ts=2020-10-01T10:08:27.517032783Z caller=repocachemanager.go:215 component=warmer canonical_name=index.docker.io/calico/pod2daemon-flexvol auth={map[]} warn="aborting image tag fetching due to rate limiting, will try again later"
ts=2020-10-01T10:09:52.143706675Z caller=warming.go:206 component=warmer updated=calico/pod2daemon-flexvol successful=950 attempted=959
ts=2020-10-01T10:09:55.351501856Z caller=warming.go:198 component=warmer info="refreshing image" image=calico/node tag_count=4498 to_update=1 of_which_refresh=0 of_which_missing=1
ts=2020-10-01T10:09:55.527976381Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/calico/node auth={map[]} warn="manifest for tag test missing in repository calico/node" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2020-10-01T10:09:55.528086884Z caller=warming.go:206 component=warmer updated=calico/node successful=0 attempted=1
ts=2020-10-01T10:09:55.530967292Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-10-01T10:10:18.634299553Z caller=warming.go:198 component=warmer info="refreshing image" image=calico/pod2daemon-flexvol tag_count=1048 to_update=9 of_which_refresh=9 of_which_missing=0
ts=2020-10-01T10:10:19.664735182Z caller=warming.go:206 component=warmer updated=calico/pod2daemon-flexvol successful=9 attempted=9
ts=2020-10-01T10:10:22.03419714Z caller=warming.go:198 component=warmer info="refreshing image" image=calico/node tag_count=4498 to_update=1 of_which_refresh=0 of_which_missing=1
ts=2020-10-01T10:10:22.487582619Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/calico/node auth={map[]} warn="manifest for tag test missing in repository calico/node" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2020-10-01T10:10:22.487719048Z caller=warming.go:206 component=warmer updated=calico/node successful=0 attempted=1
ts=2020-10-01T10:10:22.49084192Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-10-01T10:10:22.623340827Z caller=images.go:106 component=sync-loop workload=demo:deployment/podinfo container=nginx repo=nginx pattern=glob:* current=nginx warning="image with zero created timestamp" current="nginx (0001-01-01 00:00:00 +0000 UTC)" latest="nginx:1.18-perl (2020-09-10 12:34:47.735236873 +0000 UTC)" action="skip container"
ts=2020-10-01T10:11:11.798260151Z caller=warming.go:198 component=warmer info="refreshing image" image=calico/node tag_count=4498 to_update=9 of_which_refresh=8 of_which_missing=1
ts=2020-10-01T10:11:12.393410733Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/calico/node auth={map[]} warn="manifest for tag v3.14.2-1-ge7f0620 missing in repository calico/node" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2020-10-01T10:11:12.878356264Z caller=warming.go:206 component=warmer updated=calico/node successful=8 attempted=9
ts=2020-10-01T10:11:12.881677441Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-10-01T10:11:13.023112554Z caller=images.go:106 component=sync-loop workload=demo:deployment/podinfo container=nginx repo=nginx pattern=glob:* current=nginx warning="image with zero created timestamp" current="nginx (0001-01-01 00:00:00 +0000 UTC)" latest="nginx:1.18-perl (2020-09-10 12:34:47.735236873 +0000 UTC)" action="skip container"
ts=2020-10-01T10:12:06.990743669Z caller=warming.go:198 component=warmer info="refreshing image" image=calico/node tag_count=4498 to_update=1 of_which_refresh=0 of_which_missing=1
ts=2020-10-01T10:12:07.416073533Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/calico/node auth={map[]} warn="manifest for tag test missing in repository calico/node" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2020-10-01T10:12:07.416206918Z caller=warming.go:206 component=warmer updated=calico/node successful=0 attempted=1
ts=2020-10-01T10:12:07.419585023Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-10-01T10:12:07.563545473Z caller=images.go:106 component=sync-loop workload=demo:deployment/podinfo container=nginx repo=nginx pattern=glob:* current=nginx warning="image with zero created timestamp" current="nginx (0001-01-01 00:00:00 +0000 UTC)" latest="nginx:1.18-perl (2020-09-10 12:34:47.735236873 +0000 UTC)" action="skip container"
ts=2020-10-01T10:13:17.018654753Z caller=loop.go:134 component=sync-loop event=refreshed url=ssh://git@github.com/axelgobletbdr/flux-get-started branch=master HEAD=c4d4cfb36510c592d1e0b11ab4c5ecd39f1e2220
ts=2020-10-01T10:13:19.864872698Z caller=warming.go:198 component=warmer info="refreshing image" image=calico/node tag_count=4498 to_update=1 of_which_refresh=0 of_which_missing=1
ts=2020-10-01T10:13:20.119352418Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/calico/node auth={map[]} warn="manifest for tag test missing in repository calico/node" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"
ts=2020-10-01T10:13:20.119812318Z caller=warming.go:206 component=warmer updated=calico/node successful=0 attempted=1
ts=2020-10-01T10:13:20.123373811Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-10-01T10:13:20.265936425Z caller=images.go:106 component=sync-loop workload=demo:deployment/podinfo container=nginx repo=nginx pattern=glob:* current=nginx warning="image with zero created timestamp" current="nginx (0001-01-01 00:00:00 +0000 UTC)" latest="nginx:1.18-perl (2020-09-10 12:34:47.735236873 +0000 UTC)" action="skip container"
ts=2020-10-01T10:13:22.455208052Z caller=sync.go:61 component=daemon info="trying to sync git changes to the cluster" old=c4d4cfb36510c592d1e0b11ab4c5ecd39f1e2220 new=c4d4cfb36510c592d1e0b11ab4c5ecd39f1e2220
ts=2020-10-01T10:13:22.791713321Z caller=sync.go:540 method=Sync cmd=apply args= count=6
ts=2020-10-01T10:13:22.916634144Z caller=sync.go:606 method=Sync cmd="kubectl apply -f -" took=124.878654ms err=null output="namespace/demo unchanged\nnamespace/nginx configured\nservice/podinfo unchanged\ndeployment.apps/nginx configured\ndeployment.apps/podinfo configured\nhorizontalpodautoscaler.autoscaling/podinfo unchanged"
```

**Additional context**

- Flux version: 1.20.2
- Kubernetes version: 1.19.0
- Git provider: github
- Container registry provider: public images (docker hub I suppose?)

**Comment by axelgobletbdr** [comment] 2020-10-02 08:32
Hmm, after thinking about this for a while, I think it could be quite hard to achieve. How do we differentiate manual edits from e.g. mutating webhooks? I guess that the label bug does not really apply here then.

**Comment by rieger-jared** [comment] 2020-10-05 08:16
Running into this issue as well, @axelgobletbdr I think you're right, it does make sense, however, I wonder if anyone knows how to reenable syncing for these resources. Have you figured out something?

**Comment by axelgobletbdr** [comment] 2020-10-07 06:10
Hey @rieger-jared I have not found a solution yet. I do not know whether this will supported any time soon. As I mentioned in my second comment, we would have to differentiate between edits that are meant to happen (mutating webhooks etc), and human errors. For now, we should just stay away from manual editing when using Flux.

**Comment by rieger-jared** [comment] 2020-10-07 09:28
@axelgobletbdr I was able to solve my issue through the `fluxctl` CLI. In my case, there was a deployment that was halting the flux operator. running `fluxctl list-workloads --all-namespaces` showed that there was a faulty manifest that it couldn't parse. After fixing the manifest, flux was able to continue with its function. I'm still not sure though what happens when one edits a resource manually in the cluster. 

I think it might still be useful to maybe have a disengage "switch" for a deployment. however, I can understand why the developers don't want to do this as it goes against the whole git ops approach. I think I will be more stringent with manual edits. perhaps disabling editing rights for a resource that is in the flux repo.

**Comment by kingdonb** [comment] 2021-02-16 18:21
It seems like the issue isn't that flux won't restore the original state once the original manifest object has been modified, it's that you've added something to the config which the apply semantics of Flux won't overwrite because it isn't in conflict with any settings on your original YAML. I'm not completely sure I understand. If you add another annotation to the cluster that isn't in your flux yaml manifests either, Flux is not going to erase that annotation either because it uses `kubectl apply`.

This is the same as when your cluster adds additional fields like creationTimestamp and other values you probably didn't specify in your declarative YAML definition, they are not in conflict so `kubectl apply` leaves them alone.

**Comment by kingdonb** [comment] 2021-08-02 15:35
I think this is still an open issue for Flux v2, some users would like to use `kubectl replace` rather than `kubectl apply` for the stronger drift detection and correction capability that it would afford, among other reasons:

* https://github.com/fluxcd/flux2/discussions/1382

It is unlikely to get addressed here, for Flux v1, as of June the Flux v1 codebase is formally superseded, since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!

**Closed by kingdonb** 2021-08-02 15:35 UTC
Labels: blocked-needs-validation, bug
