### ISSUE TITLE
an error on the server (\"unknown\") has prevented the request from succeeding

### ISSUE THREAD

**Issue by cmanzi** [fluxcd/flux#3185] opened 2020-07-09 19:46 UTC
**Describe the bug**

When trying to install Flux 1.20.0 on a new EKS cluster (1.16.8), it cannot sync the resources to the cluster and gives the following error:

```
{"caller":"loop.go:108","component":"sync-loop","err":"collating resources in cluster for sync: an error on the server (\"unknown\") has prevented the request from succeeding","ts":"2020-07-09T19:28:40.623325982Z"}
```

I do not get any errors when using `kubectl` outside of flux, and I can successfully apply all resources in the repo without any errors. I have run this setup with a Kops cluster (1.15.7) with no issues, it is only since switching to EKS that this problem has occurred. 

RBAC is properly, and I can run `kubectl` successfully from within the flux pod.

**To Reproduce**

Steps to reproduce the behaviour:

Install fluxcd 1.20.0 on EKS 1.16.8

**Expected behavior**

Flux successfully syncs resources.

**Logs**

```
{"auth":"{map[]}","caller":"warming.go:154","canonical_name":"index.docker.io/fluxcd/flux","component":"warmer","err":"Get https://index.docker.io/v2/: x509: certificate signed by unknown authority","ts":"2020-07-09T19:28:27.417420915Z"}
{"HEAD":"83801cb4ea86ce26c905876ff5710fa2cca72240","branch":"[redacted]","caller":"loop.go:134","component":"sync-loop","event":"refreshed","ts":"2020-07-09T19:28:38.176727819Z","url":"ssh://[redacted]}
{"caller":"sync.go:60","component":"daemon","info":"trying to sync git changes to the cluster","new":"83801cb4ea86ce26c905876ff5710fa2cca72240","old":"","ts":"2020-07-09T19:28:38.199621711Z"}
{"caller":"loop.go:108","component":"sync-loop","err":"collating resources in cluster for sync: an error on the server (\"unknown\") has prevented the request from succeeding","ts":"2020-07-09T19:28:40.623325982Z"}
```

**Additional context**

Config:
```
        - --manifest-generation=true
        - --memcached-hostname=flux-memcached.flux-system
        - --memcached-service=
        - --git-poll-interval=2m
        - --sync-interval=2m
        - --log-format=json
        - --k8s-verbosity=1
        - --k8s-secret-volume-mount-path=/etc/fluxd/ssh
        - --git-url=[redacted]
        - --git-path=deploy/flux
        - --git-branch=[redacted]
        - --git-email="[redacted]
        - --git-user="Flux Service"
        - --sync-garbage-collection
        - --sync-state=secret
```

- Flux version: 1.20.0
- Kubernetes version: 1.16.8
- Git provider: bitbucket
- Container registry provider:

**Comment by sdickhoven** [comment] 2020-11-20 01:35
this seems to happen when flux catches up to itself (on larger clusters). try relaxing the `--git-poll-interval`.

i also recommend making the `--sync-interval` longer than the poll interval (e.g. 2x). sync is for reconciliation of in-cluster changes which should be rare.

**Comment by sdickhoven** [comment] 2020-11-21 01:01
hmm. that error is back. so i guess what i said above is not correct.

```
{"caller":"loop.go:108","component":"sync-loop","err":"collating resources in cluster for sync: an error on the server (\"unknown\") has prevented the request from succeeding","ts":"2020-11-21T00:56:53.801766369Z"}
```

Flux version: 1.20.2
Kubernetes version: v1.16.13-eks-2ba888

**Comment by kingdonb** [comment] 2021-02-18 23:47
Is this reproduced in newer versions of Flux v1? We are on v1.21.2 now. I am not in a position currently to reproduce the issue.

**Comment by sdickhoven** [comment] 2021-02-19 00:13
for us the problem cleared apparently by itself, though it is unclear exactly how/why.

the problem cleared shortly after we manually deleted/deployed a subset of the resources that are normally deployed via flux.

i should mention that the particular eks cluster where this problem persisted for several days sees many non-flux changes every day. so i suspect that manually doing things to those resources that were created/managed by flux somehow "loosened the knot".

the best hypothesis i can come up with right now is that the eks control plane was in a bad state somehow.

we had upgraded to flux 1.21.0 when we were still seeing this issue but that did not resolve the problem.

however, once the problem cleared, we never sawed it again.

**Comment by sdickhoven** [comment] 2021-02-19 00:21
i should also mention that we relaxed the sync interval for most of our flux instances to >1h.

i even encouraged everyone to pick a prime number of minutes for the sync interval to ensure that sync intervals are co-prime. that way, two (or more) flux instances will almost never sync at the same time.

maybe there was some rate limiting logic in eks that was engaged by the frequent syncs that only cleared after ~24h hours... because about one day _before_ the problem cleared we had backed off the sync period.

...so that would be another plausible hypothesis.

**Comment by kingdonb** [comment] 2021-02-19 15:41
Manually changing resources that are installed by Flux is counter-indicated and prone to creating issues like the one you mentioned. It is good to hear a strategy was found that helped clear the issue. Co-prime strategy sounds like a good one.

Since the issue has cleared and we no longer have a path to reproduce or active exemplar failure which needs resolving that I'm aware of, I'm going to go ahead and close this.

If this is still affecting you (@cmanzi), I will be happy to reopen here, and/or troubleshoot with you in the #flux slack channel on CNCF, but in the interest of reducing the number of open issues not directly related to supporting Flux v1 in maintenance mode down to something manageable, and respecting you may have moved on already even if this problem was never solved, I will go ahead and close out this issue for now.

**Closed by kingdonb** 2021-02-19 15:41 UTC
Labels: blocked-needs-validation, bug

**Comment by sdickhoven** [comment] 2021-04-21 15:31
i just had this happen again. flux version `1.21.0`.

i was once again able to clear the issue by manually deploying a subset of the resources that are normally managed by flux.

what happens in that case is that all the labels/annotations added by flux during deployment are removed from those resources.

i suspect that this error has something to do with how flux enumerates resources when trying to do an apply; specifically wrt those labels/annotations.

since our manifests are very stable (we don't do registry scanning and hardly ever delete resources), it is safe for us to remove all those labels/annotations. after all, flux will just re-add them once it successfully runs again.

**Comment by kingdonb** [comment] 2021-04-21 18:07
@sdickhoven If you want to try debugging this further with me, please reopen as a new issue.

If I understood that correctly, you were able to produce the issue again and you have the workaround in a state that you can cope with.

Please open another issue @sdickhoven and include enough information to reproduce the situation you've described (eg. a Flux repo and `fluxctl install` or helm values.yaml for your Flux installation), or if we think there just should be better documentation around this workaround, I would be happy to review a pull request for the docs to that effect.

If you think that something other than more docs are needed, we can discuss it further.

**Comment by sdickhoven** [comment] 2021-04-21 19:47
hi @kingdonb

unfortunately i can't reproduce the problem. it crops up very rarely but once it does it tends to persist.

i just wanted to share my hypothesis re labels/annotations but there's not really much more info i can supply other than what i have observed.

the only difference in our setup from https://github.com/fluxcd/flux/issues/3185#issuecomment-731480175 is:
flux: `1.21.0`
kubernetes: `v1.18.9-eks-d1db3c`
sync-interval: `71m`

**Comment by sdickhoven** [comment] 2021-04-21 19:50
this may be some weird eks bug by the way. so i'm not going to open another issue. i just wanted to share a bit of additional info in case anyone finds it useful/helpful.

thanks.

**Comment by sdickhoven** [comment] 2021-04-30 02:26
turns out that we had a dodgy api service in our clusters: `v1alpha1.metrics.smi-spec.io`.

this is something that's optionally installed by linkerd.

after doing

```
$ kubectl delete apiservice v1alpha1.metrics.smi-spec.io
```

flux started deploying again.

credit goes to @mpessas for figuring this out.

maybe this will be useful information for you all to possibly work around issues caused by dodgy api services (or maybe add some helpful log messages to aid in identifying what might be going on).
