### ISSUE TITLE
When are you likely to create a new helm chart?

### ISSUE THREAD

**Issue by james-gonzalez** [fluxcd/flux#3412] opened 2021-02-02 15:26 UTC
We are looking specifically for it to include: https://github.com/fluxcd/flux/releases/tag/1.21.1

Thanks!

**Comment by kingdonb** [comment] 2021-02-02 17:45
Thanks @james-gonzalez for asking about this. I am not in a position to promote the release myself, however I can see that I mention it tomorrow morning at the FluxCD meeting and that it gets added to the agenda.

In the mean time, hopefully you have found the parameter `image.tag` in it so that you can install the updated version in the chart:

```bash
helm upgrade --install fluxcd/flux --set image.tag=1.21.1
```

Flux v1 is in maintenance mode (#3320) and it receives only limited updates. I think it is likely that the chart update will be delayed until after any open PRs related to chart changes can be closed or addressed in the update.

Those open PR issues I've identified that may touch the chart are:

#3409 #3293 #3161 #3164 #3101 #3046 #3052 #3397 #3131 #3325 – if there are any of these issues that you would like to see included along with priority other than the simple version bump, please let us know.

I am not in the position of maintainer it is not something I can execute on my own without help, and I don't want to distract the development effort any more than necessary by running the release machinery more than needed. I am not sure how many of these will merge rather than close, but my aim is to leave none behind and get all in shape for the next chart release. Some will get closed, as we cannot reasonably expect to include any breaking changes while the series is in maintenance mode.

If there are no new bugs and or urgent changes required, we may expect all future developments to be in the new [Flux v2](https://github.com/fluxcd/flux2). Please feel free to reach out separately (eg. on the CNCF slack in #flux, or in one of the suggested venues on the [new support page](https://fluxcd.io/support/) if there is anything currently blocking you from being able to migrate your workloads to Flux v2. We want to ensure every use case is at least feature parity and hopefully improved.

There are migration guides now for [flux v1](https://toolkit.fluxcd.io/guides/flux-v1-migration/) and [helm operator](https://toolkit.fluxcd.io/guides/helm-operator-migration/) if you want to try, the maintainers have published these recently and they should be release quality. If there are any hiccups or challenges we will appreciate if you are willing to let us know.

**Comment by james-gonzalez** [comment] 2021-02-02 17:54
@kingdonb thanks for the prompt and detailed response. Please let me know what the outcome is when you can. I will in the meantime try overriding the image.tag property to test out the nee changes.

**Comment by kingdonb** [comment] 2021-02-04 13:52
Working on this right now. I've opened a branch `chart-bump` and will be sending it in a PR momentarily, I want to make sure I note everything since some major things have been changed out under the hood. Nothing that should have any negative effects on any users, but since no chart release was made concurrently with `1.21.1`, the changelog for the chart release will have to go back even further, to the `chart-1.6.0` tag.

I am planning to call this `1.6.1`. It should be ready for PR later this morning, once past CI I think it would be published right away!

**Comment by kingdonb** [comment] 2021-02-04 15:59
There is #3416 open now, with a 1.6.1 version of the chart released with it, that carries this new image 1.21.1. It is still running CircleCI build (or is it waiting for someone to authorize the build to begin?)

CircleCI should proceed with generating and publishing all of the downstream release artifacts automatically as soon as this is merged, and once a tag is pushed as `chart-1.6.1`, this is my first time doing a release, but this is according to the instructions in the [releasing.md](https://github.com/fluxcd/flux/blob/master/internal/docs/releasing.md) from fluxcd/flux.

So as soon as that finishes, you can run `helm repo update` and be able to proceed with installing the new release.

Hoping this also can solve #1766, I don't have verification of complete steps to reproduce (I did not see #1766 myself, but others have seen it every time) it seems like there is an issue in the chart's `memcached` service which was missing a `namespace` metadata that was resolved for this release, which has been overlooked for a long time, and may be related.

**Comment by kingdonb** [comment] 2021-02-05 16:43
The chart with app version 1.21.1 has been released, thank you for bringing attention to this!

#3418 is an open issue for planning of the next release. If you have any further open PRs for non-breaking changes that have not been merged yet and want to get attention to them, please let me know there. If we are able to put out a new release next week (1.21.2) then I will be sure the chart revision gets bumped also!

**Closed by kingdonb** 2021-02-05 16:43 UTC
