### ISSUE TITLE
Memcached PVC/HA Support

### ISSUE THREAD

**Issue by coultenholt** [fluxcd/flux#3327] opened 2020-10-09 21:22 UTC
Hello,

We have a fairly large test environment with up to 100 or so unique images, that could contain upwards of 1000 tags depending on the image. We have been rate limited on our Docker hub to around 10 req/sec. So with this an initial start up of flux and memcached, it could take almost 3 hours to populate the db entirely in memcached (100 images * 1000 tags / 10 reps / 60 seconds). This issue will continue to compound on itself until the the refresh interval is calculated to be long enough where its not trying to continuously refresh each tag, as they aren't changing.

So essentially in set ups like this, a memcached pod restarting and losing all data could be catastrophic. As it would quite a long time before flux has repopulated the db and established high enough refresh times for each tag.
 
A possible solution is simply creating/enabling memcached to use a backing PVC. This will ensure that even if memcached is restart it will retain its data, thus making it where flux doesn't have to reestablish the entire db and refresh times for each image/tag.

Wdyt?

**Comment by kingdonb** [comment] 2021-02-12 23:22
The re-architecture of Flux v2 was designed to skirt around this issue and several other related issues. Images can only be ordered in one of two ways: by innate ordering in the tag string (eg semver/alphabetic/numeric order) or by build timestamps.

When pulling a repository from the Docker registry in Flux v1 for image automation, the first step is to pull the list of tags (this is a single, or at least paginated remote call, fetch tag list index, which is not rate limited in the same way as pulling image layers) and then to pull the metadata for each image layer, which includes the build timestamp.

In Flux v2, because of this limitation, using build timestamps was abandoned for the new image automation controller's design. In this new architecture, there is no need for memcached because the image tag lists are comparatively small and cheap to fetch again, so they can be scalably stored in an in-process memory database instead. This can be done quickly and efficiently by comparison, the new architecture has better scaling as a main benefit.

Please take a look at the docs regarding Image Automation in Flux v2 and see if an upgrade might be possible:

https://toolkit.fluxcd.io/guides/image-update/

For an idea of what else has changed with the new architecture, please see this doc:

https://toolkit.fluxcd.io/faq/#what-are-significant-new-differences-between-flux-v1-and-flux-v2

If you want to provide a PR that implements this, for memcached in the flux chart, as a non-breaking change to add a PV, I would consider it for inclusion in a maintenance release, however the bulk of developer efforts at this point are focused on Flux v2, as Flux v1 is in maintenance mode.

Please let us know if there is something blocking your migration to the new version, we believe that for most use cases at this point feature parity is close, or in some cases has already been reached. Thanks for using Flux!

**Comment by kingdonb** [comment] 2021-06-09 12:38
I am closing your issue, but you are welcome to resubmit as a PR if you are interested in a code review.

I cannot guarantee any new features are going to be merged, but even if not possible, I will be happy to give feedback and suggest improvements.

Thanks for using Flux!

**Closed by kingdonb** 2021-06-09 12:38 UTC
Labels: flux2
