### ISSUE TITLE
Support arbitrary resources for "fluxcd.io/automated" annotation

### ISSUE THREAD

**Issue by heprotecbuthealsoattac** [fluxcd/flux#2518] opened 2019-10-15 16:49 UTC
**Describe the feature**

It looks like fluxcd can't automatically update image for knative's service resource. I'd like fluxcd to be able to do that.
For reference:
```
ts=2019-10-15T16:44:21.722165052Z caller=kubernetes.go:147 warning="automation of this resource kind is not supported" resource=app:service/frontend
```

**Comment by squaremo** [comment] 2019-10-17 12:28
It's not a huge leap to fluxd being able to update arbitrary resources -- there's already a scheme for pointing at the field to update, used for `HelmRelease`, which could be generalised.

_Today_, however, I think you would have to use [Kustomize via `.flux.yaml`](https://docs.fluxcd.io/en/stable/references/fluxyaml-config-files.html); but beware, there are problems with this approach (e.g., #2428).

**Comment by squaremo** [comment] 2019-10-17 12:30
If you don't mind, I'm going to make this issue a little more general, since it's something we'd like to address for other kinds of custom resource.

**Comment by stefanprodan** [comment] 2019-10-17 12:48
Duplicate of: #1794

**Comment by Morriz** [comment] 2020-02-17 17:17
We would love to see this enhancement, which could modify and redeploy any resource matching the annotations.

**Comment by robinbraemer** [comment] 2020-08-16 19:12
We also need this to work with CRDs! We are using [Agones](https://github.com/googleforgames/agones) for instance and we 
 need the image to auto update for the GameServer in a [Fleet](https://github.com/googleforgames/agones/blob/master/examples/fleet.yaml).

**Comment by kingdonb** [comment] 2021-07-31 16:15
Flux v2 does support automation for arbitrary resources including custom resources now:

https://fluxcd.io/docs/guides/image-update/#configure-image-update-for-custom-resources

Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!

Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!

**Closed by kingdonb** 2021-07-31 16:15 UTC
Labels: enhancement, flux2
