### ISSUE TITLE
Documentation refers to unused key

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/flux#2274] opened 2019-07-19 16:15 UTC
@2opremio @hiddeco. Let's start over.

The documentation of the Helm chart values (line 264 of https://github.com/fluxcd/flux/blob/master/chart/flux/README.md) refers to the key
`helmOperator.git.secretName` that is not used in the actual helm chart.  The comment speaks of this key superseding another key, but the code does not reflect that.

Instead, the key `git.secretname` is used in the deployment file, with no mention of the new key `helmOperator.git.secretName` .

There are two places in the helm chart that reference `git.secretName`: 
https://github.com/fluxcd/flux/blob/master/chart/flux/templates/deployment.yaml#L52
https://github.com/fluxcd/flux/blob/master/chart/flux/templates/deployment.yaml#L158

These should be updated to recognize the new key name **or** the new key name should be eliminated from the documentation.

Since this is a **choice** that needs to be made by you, I do not submit a PR with the one I prefer, but defer the decision to you.

Thank you for providing an excellent open source project.  I hope that this helps.

**Comment by hiddeco** [comment] 2019-07-19 16:27
The `helmOperator.git.secretName` is only used in the deployment file for the Helm operator, it _supersedes the Flux key_, see: https://github.com/fluxcd/flux/blob/334756698837b92c14a5c70550cd70ba1f9030f4/chart/flux/templates/helm-operator-deployment.yaml#L52-L58.

**Comment by derrickburns** [comment] 2019-07-19 16:31
So the lines I refer to above are ignored?

**Comment by hiddeco** [comment] 2019-07-19 16:33
If you only configure the `git.secretName`, both Flux and the Helm operator will use this key.

If you configure both the `git.secretName` and the `helmOperator.git.secretName`, Flux will use the former and the Helm operator the latter.

**Comment by derrickburns** [comment] 2019-07-19 16:45
That explains the problem I had. 

I only configured 'helmOperator.git.secretName'. 

So is the value intended to be specified twice?  Or is that
An unintended consequence of having two different deployments
In the same helm chart?

In any case, as a user I was confused. I expect to 
only need to provide a value once. Therefore,
When I see "supercedes" I interpret that as "use this new way and don't use the old way".

**Comment by hiddeco** [comment] 2019-07-19 17:15
> So is the value intended to be specified twice? Or is that an unintended consequence of having two different deployments in the same helm chart?

No, it is still possible to configure only one key by just setting the `git.secretName`.

> I expect to only need to provide a value once. Therefore, when I see "supersedes" I interpret that as "use this new way and don't use the old way".

What would be a less confusing description for you?

**Comment by derrickburns** [comment] 2019-07-19 19:17
Having only one way to specify the secret name would be most clear.

What is the point of an override if the old name is still required? :)

**Comment by hiddeco** [comment] 2019-07-20 10:53
> What is the point of an override if the old name is still required? :)

Because otherwise you would not have the ability to define a different key for the Helm operator. Which is not an option if for example, your Helm charts are located in a different repository than your Kubernetes resources, as GitHub deploy keys can only be active for one repository at a time.

**Comment by derrickburns** [comment] 2019-07-21 20:47
It seems that if you allow that use case then all the repos updated or read by the helm operator would need the same key. How is this any different that requiring all repos to recognize the same key?

**Comment by hiddeco** [comment] 2019-07-22 08:54
> It seems that if you allow that use case then all the repos updated or read by the helm operator would need the same key.

The Helm operator does not make any updates, Flux does. It is perfectly fine to have one repository with your `HelmRelease` resources for Flux (which it updates with a read-write key), and a different repository with charts and a read-only key.

I am going to close this to get it of our radar, as per the above explanations it is not a bug.

**Closed by hiddeco** 2019-07-22 08:54 UTC
Labels: blocked-needs-validation, bug

**Comment by squaremo** [comment] 2019-07-22 10:27
> It seems that if you allow that use case then all the repos updated or read by the helm operator would need the same key. How is this any different that requiring all repos to recognize the same key?

This is a fair question. The chart caters for two possibilities:

 1. You are using the same repo for your YAMLs (for fluxd) and for your charts (for helm-op)
 2. You are using one repo for YAMLs, and another repo for charts.

It doesn't cater to people using many repos for charts, which is supported by the helm-op executable, but not very easy to set up in a pod config.
